-- ============================================================================
-- GTQC LABORATORIO — ESQUEMA DE BASE DE DATOS  ·  v3.0
-- ============================================================================
-- Archivo 1 de 6.  Orden de carga obligatorio:
--     00_schema.sql  →  01_functions.sql  →  02_triggers.sql
--     →  03_indexes_views.sql  →  04_seeds.sql  →  05_seed_ensayos.sql
--     →  (opcional) 99_verificacion.sql
--
-- Motor de referencia: PostgreSQL 14+ (probado en 16.13).
--
-- QUÉ CAMBIA RESPECTO DE v2 (resumen; el detalle está en docs/AUDITORIA_BD_v3.md)
--   · IDs:        SERIAL → GENERATED BY DEFAULT AS IDENTITY; los números
--                 existentes NO cambian. Se agrega public_id UUID a las
--                 entidades que la API expondrá (evita IDOR por id secuencial).
--   · Códigos:    el ID técnico, el ID público y el CÓDIGO DE NEGOCIO
--                 (SU-01, COT-2026-001) son tres cosas distintas y separadas.
--   · Correlativos: tabla `correlativos` + fn_siguiente_correlativo() atómico.
--                 Se elimina todo MAX(...)+1 y toda dependencia del frontend.
--   · Dominios:   los estados, unidades y proveedores dejan de ser VARCHAR
--                 libre y pasan a DOMAIN con CHECK.
--   · Integridad: CHECK de dinero/cantidades/RUC/DNI/email, FK compuesta
--                 (empresa_id, contacto_id) y totales verificados por CHECK.
--   · Snapshots:  el ítem de cotización congela además categoría, subcategoría,
--                 unidad y es_paquete, para que el dashboard no pierda historia.
--   · Auditoría:  usuario real vía current_setting('app.usuario_id'), campos
--                 cambiados, IP, y tabla `auditoria` append-only.
--   · Soft delete: una sola convención (`activo BOOLEAN`) en todas las tablas.
--   · Multi-tenant: NO se implementa aquí. Cada tabla queda marcada como
--                 GLOBAL o TENANT-SCOPED y todos los UNIQUE que deberán cambiar
--                 de ámbito llevan nombre propio, para que
--                 migrations/0003_multitenant_habilitar.sql sea mecánico.
--
-- CONVENCIÓN DE ETIQUETAS (se respeta en todo el archivo):
--     [GLOBAL]        la fila es del producto, no de un laboratorio cliente.
--     [TENANT-SCOPED] la fila pertenecerá a un tenant cuando exista el SaaS.
--     [HÍBRIDA]       hay filas de producto (plantilla base) y filas del tenant.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 0. CONTROL DE VERSIONES DEL ESQUEMA
-- ----------------------------------------------------------------------------
-- Sin esto no hay forma de saber qué versión está desplegada en el servidor.
-- Toda migración futura debe registrar su fila aquí.  [GLOBAL]
CREATE TABLE schema_migrations (
    version      VARCHAR(20)  PRIMARY KEY,           -- '0001', '0002', '0003'
    nombre       VARCHAR(140) NOT NULL,
    aplicada_en  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    nota         VARCHAR(300)
);


-- ----------------------------------------------------------------------------
-- 1. DOMINIOS (la BD como primera línea de defensa)
-- ----------------------------------------------------------------------------
-- Se usan DOMAIN sobre VARCHAR en vez de ENUM nativo: se leen igual, se
-- validan igual, y son portables si algún día se evalúa otro motor.

-- Máquina de estados de la cotización:
--   borrador → emitida → aceptada | rechazada | cancelada
CREATE DOMAIN dom_estado_cotizacion AS VARCHAR(12)
    CHECK (VALUE IN ('borrador','emitida','aceptada','rechazada','cancelada'));

CREATE DOMAIN dom_unidad AS VARCHAR(10)
    CHECK (VALUE IN ('UND','PUNT.','DÍA','M2','M3','ML','KG','GLB'));

CREATE DOMAIN dom_descuento_tipo AS VARCHAR(12)
    CHECK (VALUE IN ('porcentaje','monto'));

CREATE DOMAIN dom_proveedor_nube AS VARCHAR(20)
    CHECK (VALUE IN ('google_drive','office365'));

CREATE DOMAIN dom_estado_integracion AS VARCHAR(12)
    CHECK (VALUE IN ('activa','revocada','expirada'));

CREATE DOMAIN dom_tipo_documento AS VARCHAR(24)
    CHECK (VALUE IN ('cotizacion_pdf','certificado_ensayo','orden_compra','otro'));

CREATE DOMAIN dom_origen_documento AS VARCHAR(10)
    CHECK (VALUE IN ('local','nube'));

CREATE DOMAIN dom_accion_auditoria AS VARCHAR(8)
    CHECK (VALUE IN ('INSERT','UPDATE','DELETE'));

-- Identificadores formales peruanos. RUC: 11 dígitos, inicia en 10/15/16/17/20.
CREATE DOMAIN dom_ruc AS VARCHAR(11)
    CHECK (VALUE ~ '^(10|15|16|17|20)[0-9]{9}$');

CREATE DOMAIN dom_dni AS VARCHAR(8)
    CHECK (VALUE ~ '^[0-9]{8}$');

CREATE DOMAIN dom_email AS VARCHAR(150)
    CHECK (VALUE ~* '^[^@[:space:]]+@[^@[:space:]]+\.[A-Za-z]{2,}$');

CREATE DOMAIN dom_telefono AS VARCHAR(25)
    CHECK (VALUE ~ '^[-0-9+() ]{6,25}$');

CREATE DOMAIN dom_color_hex AS VARCHAR(7)
    CHECK (VALUE ~ '^#[0-9a-fA-F]{6}$');

-- Dinero del sistema: nunca negativo, siempre 2 decimales.
CREATE DOMAIN dom_monto AS NUMERIC(12,2) CHECK (VALUE >= 0);
CREATE DOMAIN dom_precio AS NUMERIC(10,2) CHECK (VALUE >= 0);


-- ----------------------------------------------------------------------------
-- 2. SEGURIDAD: ROLES Y USUARIOS
-- ----------------------------------------------------------------------------
-- Aquí NO se implementa login ni JWT (eso es fase de backend). Solo queda el
-- modelo listo para soportarlos sin migrar nada después.

-- [GLOBAL] Los 4 roles son del producto, iguales para todos los laboratorios.
CREATE TABLE roles (
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo       VARCHAR(20)  NOT NULL,        -- 'admin','comercial','laboratorio','lectura'
    nombre       VARCHAR(60)  NOT NULL,
    descripcion  VARCHAR(220),
    es_sistema   BOOLEAN      NOT NULL DEFAULT TRUE,   -- rol base: no se elimina
    CONSTRAINT uq_roles_codigo UNIQUE (codigo)
);

-- [TENANT-SCOPED] Cada laboratorio tendrá sus propios usuarios.
-- El usuario id = 1 ('sistema') es la excepción global: es el autor de los
-- seeds y el fallback de auditoría cuando el backend no fijó app.usuario_id.
CREATE TABLE usuarios (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    nombres           VARCHAR(100) NOT NULL CHECK (btrim(nombres) <> ''),
    apellidos         VARCHAR(100) NOT NULL CHECK (btrim(apellidos) <> ''),
    email             dom_email    NOT NULL,
    rol_id            INTEGER      NOT NULL REFERENCES roles(id) ON DELETE RESTRICT,
    -- Preparado para autenticación futura. Guarda SOLO un hash (Argon2id o
    -- bcrypt). Jamás una contraseña, jamás un token. NULL = sin acceso aún.
    password_hash     VARCHAR(255),
    ultimo_acceso_en  TIMESTAMPTZ,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    desactivado_en    TIMESTAMPTZ,
    desactivado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_por        INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_usuarios_public_id UNIQUE (public_id),
    -- [MT] Bajo multi-tenant pasa a UNIQUE (tenant_id, lower(email)).
    CONSTRAINT ck_usuarios_desactivado CHECK (activo OR desactivado_en IS NOT NULL)
);
CREATE UNIQUE INDEX uq_usuarios_email ON usuarios (lower(email));


-- ----------------------------------------------------------------------------
-- 3. CLIENTES: EMPRESA (RUC) / CONTACTO / PERSONA NATURAL (DNI)
-- ----------------------------------------------------------------------------
-- Regla de negocio conservada de v2: una cotización pertenece SIEMPRE a una
-- EMPRESA (con o sin contacto) o a una PERSONA NATURAL. Nunca a ambas.
-- v3 agrega que el CONTACTO tiene que ser de ESA empresa (FK compuesta).

-- [TENANT-SCOPED] La cartera de clientes es el activo del laboratorio.
-- Dos laboratorios distintos pueden tener al mismo cliente: bajo multi-tenant
-- el RUC deja de ser único global y pasa a UNIQUE (tenant_id, ruc).
CREATE TABLE empresas (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    ruc               dom_ruc      NOT NULL,
    razon_social      VARCHAR(200) NOT NULL CHECK (btrim(razon_social) <> ''),
    direccion         VARCHAR(250),
    telefono          dom_telefono,
    email             dom_email,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_empresas_public_id UNIQUE (public_id),
    CONSTRAINT uq_empresas_ruc       UNIQUE (ruc)          -- [MT] → (tenant_id, ruc)
);

-- [TENANT-SCOPED] Personas que cotizan en nombre de una empresa.
-- uq_contactos_empresa_id existe para poder colgar de ella la FK compuesta
-- de cotizaciones: es lo que impide que una cotización de la Empresa A
-- referencie al contacto de la Empresa B. Es el mismo patrón que se usará
-- para el aislamiento por tenant.
CREATE TABLE contactos (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    empresa_id        INTEGER      NOT NULL REFERENCES empresas(id) ON DELETE RESTRICT,
    dni               dom_dni,
    nombres           VARCHAR(100) NOT NULL CHECK (btrim(nombres) <> ''),
    apellidos         VARCHAR(100) NOT NULL CHECK (btrim(apellidos) <> ''),
    cargo             VARCHAR(100),
    celular           dom_telefono,
    email             dom_email,
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_contactos_public_id  UNIQUE (public_id),
    CONSTRAINT uq_contactos_empresa_id UNIQUE (empresa_id, id),
    CONSTRAINT uq_contactos_empresa_dni UNIQUE (empresa_id, dni)
);

-- [TENANT-SCOPED] Cliente que cotiza con DNI, sin empresa registrada.
CREATE TABLE personas (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    dni               dom_dni      NOT NULL,
    nombres           VARCHAR(100) NOT NULL CHECK (btrim(nombres) <> ''),
    apellidos         VARCHAR(100) NOT NULL CHECK (btrim(apellidos) <> ''),
    celular           dom_telefono,
    email             dom_email,
    -- Texto libre a propósito: el cliente suele mencionar una empresa que
    -- todavía no está registrada. Si luego se registra, se crea la empresa
    -- y el contacto; esta columna queda como dato histórico de captación.
    empresa_asociada  VARCHAR(200),
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_personas_public_id UNIQUE (public_id),
    CONSTRAINT uq_personas_dni       UNIQUE (dni)          -- [MT] → (tenant_id, dni)
);


-- ----------------------------------------------------------------------------
-- 4. CATÁLOGO: CATEGORÍA > SUBCATEGORÍA > ENSAYO (+ PAQUETES)
-- ----------------------------------------------------------------------------
-- Reglas del modelo, todas exigidas por la BD (ver 02_triggers.sql):
--   R1. Jerarquía estricta Categoría (1) → Subcategorías (N) → Ensayos (N).
--       La categoría de un ensayo se deduce de su subcategoría, no se repite.
--   R2. Toda categoría activa tiene al menos una subcategoría activa.
--   R3. Lo que tiene historia no se borra: se desactiva (activo = FALSE).
--   R4. prefijo_codigo (SU, AG, AS, AL) arma el código del ensayo (SU-01) y
--       queda fijo en cuanto la categoría tiene ensayos.
--   R5. Nombres únicos: categoría en todo el catálogo, subcategoría dentro de
--       su categoría, sin distinguir mayúsculas.
--   R6 (v3). El número del código sale de `correlativos`, nunca de MAX()+1,
--       y NO se reutiliza aunque el ensayo se elimine.

-- [TENANT-SCOPED] Cada laboratorio define y tarifa su propio catálogo.
CREATE TABLE categorias_ensayo (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID          NOT NULL DEFAULT gen_random_uuid(),
    -- slug = identificador estable para integraciones y URLs; NO es la PK.
    slug              VARCHAR(40)   NOT NULL CHECK (slug ~ '^[a-z0-9_]{2,40}$'),
    nombre            VARCHAR(40)   NOT NULL CHECK (btrim(nombre) <> ''),
    prefijo_codigo    VARCHAR(3)    NOT NULL CHECK (prefijo_codigo ~ '^[A-Z]{2,3}$'),   -- R4
    icono             VARCHAR(10),
    color_hex         dom_color_hex,
    orden             SMALLINT      NOT NULL DEFAULT 0 CHECK (orden >= 0),
    activo            BOOLEAN       NOT NULL DEFAULT TRUE,                               -- R3
    creado_por        INTEGER       NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    actualizado_por   INTEGER       REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_categorias_public_id UNIQUE (public_id),
    CONSTRAINT uq_categorias_slug      UNIQUE (slug),             -- [MT] → (tenant_id, slug)
    CONSTRAINT uq_categorias_prefijo   UNIQUE (prefijo_codigo)    -- [MT] → (tenant_id, prefijo_codigo)
);
CREATE UNIQUE INDEX uq_categorias_nombre ON categorias_ensayo (lower(nombre));           -- R5

-- [TENANT-SCOPED]
CREATE TABLE subcategorias_ensayo (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    categoria_id      INTEGER      NOT NULL REFERENCES categorias_ensayo(id) ON DELETE RESTRICT,
    nombre            VARCHAR(40)  NOT NULL CHECK (btrim(nombre) <> ''),
    orden             SMALLINT     NOT NULL DEFAULT 0 CHECK (orden >= 0),
    activo            BOOLEAN      NOT NULL DEFAULT TRUE,                                -- R3
    creado_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_subcategorias_public_id UNIQUE (public_id),
    -- Necesaria para la FK compuesta de ensayos_catalogo: garantiza que el
    -- ensayo, su subcategoría y su categoría sean coherentes entre sí.
    CONSTRAINT uq_subcategorias_categoria_id UNIQUE (categoria_id, id)
);
CREATE UNIQUE INDEX uq_subcategorias_nombre
    ON subcategorias_ensayo (categoria_id, lower(nombre));                                -- R5

-- [TENANT-SCOPED] El corazón del sistema: cada fila es un servicio vendible.
-- es_paquete = TRUE cuando en realidad es un combo (ver paquete_componentes).
-- El precio del paquete es propio: el laboratorio da descuento por combo.
--
-- categoria_id está DENORMALIZADO a propósito y amarrado con FK compuesta a
-- (categoria_id, subcategoria_id). Motivo: el trigger que valida el prefijo
-- del código y el dashboard por categoría lo consultan en cada fila; sin esta
-- columna harían un JOIN extra y, peor, el código y la categoría podrían
-- desincronizarse al mover una subcategoría.
CREATE TABLE ensayos_catalogo (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID          NOT NULL DEFAULT gen_random_uuid(),
    -- CÓDIGO DE NEGOCIO. No es la PK y no es el id público.
    codigo            VARCHAR(12)   NOT NULL CHECK (codigo ~ '^[A-Z]{2,3}-[0-9]{2,4}$'),
    categoria_id      INTEGER       NOT NULL,
    subcategoria_id   INTEGER       NOT NULL,
    nombre            VARCHAR(220)  NOT NULL CHECK (btrim(nombre) <> ''),
    descripcion       VARCHAR(500),
    unidad            dom_unidad    NOT NULL DEFAULT 'UND',
    norma             VARCHAR(120),
    precio_base       dom_precio    NOT NULL,
    es_paquete        BOOLEAN       NOT NULL DEFAULT FALSE,
    acreditado        BOOLEAN       NOT NULL DEFAULT FALSE,   -- ISO/IEC 17025 vigente HOY
    activo            BOOLEAN       NOT NULL DEFAULT TRUE,
    -- Desde cuándo dejó de ofrecerse. Un auditor ISO 17025 pregunta esto;
    -- por eso es columna y no solo una fila en `auditoria`.
    desactivado_en    TIMESTAMPTZ,
    desactivado_por   INTEGER       REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_por        INTEGER       NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ   NOT NULL DEFAULT now(),
    actualizado_por   INTEGER       REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,
    CONSTRAINT uq_ensayos_public_id UNIQUE (public_id),
    CONSTRAINT uq_ensayos_codigo    UNIQUE (codigo),          -- [MT] → (tenant_id, codigo)
    CONSTRAINT fk_ensayos_subcategoria
        FOREIGN KEY (categoria_id, subcategoria_id)
        REFERENCES subcategorias_ensayo (categoria_id, id) ON DELETE RESTRICT,
    CONSTRAINT ck_ensayos_desactivado CHECK (activo OR desactivado_en IS NOT NULL)
);

-- [TENANT-SCOPED] APPEND-ONLY (no se actualiza; ver 02_triggers.sql).
-- Historial de acreditación: cuándo un ensayo ganó o perdió su alcance.
-- Permite responder "¿estaba SU-03 acreditado el 15/03/2024?" sin adivinar.
CREATE TABLE ensayo_acreditacion_historial (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ensayo_id         INTEGER      NOT NULL REFERENCES ensayos_catalogo(id) ON DELETE CASCADE,
    acreditado        BOOLEAN      NOT NULL,
    motivo            VARCHAR(300),
    vigente_desde     DATE         NOT NULL DEFAULT CURRENT_DATE,
    registrado_por    INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    registrado_en     TIMESTAMPTZ  NOT NULL DEFAULT now(),
    -- Dos filas para el mismo ensayo y el mismo día harían ambigua la
    -- reconstrucción histórica. Se permite una por día y por ensayo.
    CONSTRAINT uq_acreditacion_dia UNIQUE (ensayo_id, vigente_desde)
);

-- [TENANT-SCOPED] Composición de los paquetes.
-- P1. Solo un ensayo con es_paquete = TRUE puede tener componentes.
-- P2. Un componente vinculado es un ensayo INDIVIDUAL (no se anidan paquetes)
--     y nunca el propio paquete.
-- P3. El mismo ensayo no se repite dentro de un paquete (se usa `cantidad`).
-- P4. Un paquete creado o editado desde la app lleva al menos 2 componentes
--     vinculados al catálogo (fn_definir_componentes).
-- P5. Los componentes pueden venir de otra categoría (el paquete de cantera
--     de Suelos incluye "Abrasión Los Ángeles" de Concreto).
-- Compatibilidad: los componentes históricos sin ensayo equivalente vendible
-- quedan DESCRIPTIVOS (nombre + norma, ensayo_componente_id NULL).
CREATE TABLE paquete_componentes (
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ensayo_id             INTEGER      NOT NULL REFERENCES ensayos_catalogo(id) ON DELETE CASCADE,
    orden                 SMALLINT     NOT NULL DEFAULT 0 CHECK (orden >= 0),
    ensayo_componente_id  INTEGER      REFERENCES ensayos_catalogo(id) ON DELETE RESTRICT,
    cantidad              SMALLINT     NOT NULL DEFAULT 1 CHECK (cantidad BETWEEN 1 AND 999),
    nombre                VARCHAR(200),   -- solo para componentes descriptivos
    norma                 VARCHAR(120),
    CONSTRAINT ck_componente_vinculado_o_descrito
        CHECK (ensayo_componente_id IS NOT NULL OR btrim(COALESCE(nombre,'')) <> ''),
    -- Un componente vinculado no lleva texto propio: su nombre y su norma
    -- salen del ensayo (una sola fuente de verdad).
    CONSTRAINT ck_componente_sin_texto_duplicado
        CHECK (ensayo_componente_id IS NULL OR (nombre IS NULL AND norma IS NULL)),
    CONSTRAINT ck_componente_no_es_el_paquete
        CHECK (ensayo_componente_id IS NULL OR ensayo_componente_id <> ensayo_id)          -- P2
);
CREATE UNIQUE INDEX uq_paquete_componente
    ON paquete_componentes (ensayo_id, ensayo_componente_id)
    WHERE ensayo_componente_id IS NOT NULL;                                                -- P3
CREATE UNIQUE INDEX uq_paquete_componente_orden
    ON paquete_componentes (ensayo_id, orden);


-- ----------------------------------------------------------------------------
-- 5. CORRELATIVOS (FASE 6 de la auditoría)
-- ----------------------------------------------------------------------------
-- Un único lugar para todo número de negocio que deba ser consecutivo.
-- Se consume SOLO con fn_siguiente_correlativo(), que es atómico bajo
-- concurrencia (INSERT ... ON CONFLICT DO UPDATE toma el lock de la fila).
--
-- Por qué NO MAX(codigo)+1:
--   · dos usuarios simultáneos obtienen el mismo número;
--   · si se elimina la última fila, el número se reutiliza y se pierde la
--     unicidad histórica del código;
--   · obliga a recorrer la tabla de datos para emitir un número.
--
-- [HÍBRIDA → TENANT-SCOPED] `clave` ya está diseñada como texto libre para
-- que el tenant entre por PK sin rediseñar nada:
--     hoy   ('cotizacion', 'GLOBAL', '2026')
--     mañana('cotizacion', 'GLOBAL', '2026') + tenant_id en la PK
-- Así Tenant A y Tenant B pueden tener ambos COT-2026-001.
CREATE TABLE correlativos (
    ambito          VARCHAR(20) NOT NULL CHECK (ambito IN ('cotizacion','ensayo')),
    clave           VARCHAR(40) NOT NULL,      -- 'GLOBAL' | prefijo de categoría ('SU')
    periodo         VARCHAR(4)  NOT NULL,      -- '2026' para cotizaciones; '-' si no aplica
    ultimo          INTEGER     NOT NULL DEFAULT 0 CHECK (ultimo >= 0),
    actualizado_en  TIMESTAMPTZ NOT NULL DEFAULT now(),
    PRIMARY KEY (ambito, clave, periodo)       -- [MT] → (tenant_id, ambito, clave, periodo)
);


-- ----------------------------------------------------------------------------
-- 6. PLANTILLAS DE COTIZACIÓN
-- ----------------------------------------------------------------------------
-- [HÍBRIDA] Las 3 plantillas base (Estándar/Premium/Express) son del producto;
-- cada laboratorio podrá editar sus textos y crear las suyas. Bajo
-- multi-tenant: tenant_id NULL = plantilla base del producto.
CREATE TABLE plantillas_cotizacion (
    id                      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id               UUID        NOT NULL DEFAULT gen_random_uuid(),
    slug                    VARCHAR(30) NOT NULL CHECK (slug ~ '^[a-z0-9_]{2,30}$'),
    nombre                  VARCHAR(60) NOT NULL CHECK (btrim(nombre) <> ''),
    icono                   VARCHAR(10),
    validez_dias_sugerida   SMALLINT    NOT NULL DEFAULT 15
                            CHECK (validez_dias_sugerida BETWEEN 1 AND 365),
    terminos_condiciones    TEXT        NOT NULL CHECK (btrim(terminos_condiciones) <> ''),
    activo                  BOOLEAN     NOT NULL DEFAULT TRUE,
    creado_por              INTEGER     NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en               TIMESTAMPTZ NOT NULL DEFAULT now(),
    actualizado_por         INTEGER     REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en          TIMESTAMPTZ,
    CONSTRAINT uq_plantillas_public_id UNIQUE (public_id),
    CONSTRAINT uq_plantillas_slug      UNIQUE (slug)       -- [MT] → (tenant_id, slug)
);


-- ----------------------------------------------------------------------------
-- 7. COTIZACIONES
-- ----------------------------------------------------------------------------
-- [TENANT-SCOPED] Documento comercial. Nunca se elimina: se cancela.
CREATE TABLE cotizaciones (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- ID PÚBLICO: es lo que viaja en la URL y en el QR del PDF. Opaco a
    -- propósito: con un id secuencial, adivinar /cotizaciones/8 es trivial.
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    -- CÓDIGO DE NEGOCIO: lo emite fn_siguiente_numero_cotizacion(), nunca
    -- el frontend. Formato COT-YYYY-NNN.
    -- Es NULL mientras la cotización es borrador: el correlativo se consume
    -- al EMITIR, no al abrir el wizard. Así un borrador abandonado no deja un
    -- hueco en la serie oficial (y la serie oficial es la que ve el cliente).
    numero            VARCHAR(20)  CHECK (numero ~ '^COT-[0-9]{4}-[0-9]{3,5}$'),
    -- Fecha de emisión como DATE en hora de Lima. Existe porque comparar un
    -- TIMESTAMPTZ contra un DATE depende del TimeZone de la sesión: una
    -- cotización hecha 20:00 en Lima caía al día siguiente con el servidor
    -- en UTC y descuadraba el dashboard.
    fecha_emision     DATE         NOT NULL DEFAULT (now() AT TIME ZONE 'America/Lima')::date,

    -- Cliente: exactamente un bloque. Un contacto solo acompaña a una empresa.
    empresa_id        INTEGER      REFERENCES empresas(id) ON DELETE RESTRICT,
    contacto_id       INTEGER,
    persona_id        INTEGER      REFERENCES personas(id) ON DELETE RESTRICT,
    CONSTRAINT ck_cotizacion_cliente_unico CHECK (
        (empresa_id IS NOT NULL AND persona_id IS NULL) OR
        (empresa_id IS NULL AND persona_id IS NOT NULL AND contacto_id IS NULL)
    ),
    -- Aislamiento de pertenencia: el contacto tiene que ser de esa empresa.
    -- MATCH SIMPLE: si empresa_id o contacto_id es NULL la FK no se evalúa,
    -- que es justo lo que necesita el caso "empresa sin contacto" y el caso
    -- "persona natural". Es el mismo mecanismo que usará el tenant.
    CONSTRAINT fk_cotizacion_contacto_de_su_empresa
        FOREIGN KEY (empresa_id, contacto_id)
        REFERENCES contactos (empresa_id, id) ON DELETE RESTRICT,

    proyecto_nombre   VARCHAR(200) NOT NULL CHECK (btrim(proyecto_nombre) <> ''),
    validez_dias      SMALLINT     NOT NULL DEFAULT 15 CHECK (validez_dias BETWEEN 1 AND 365),
    plantilla_id      INTEGER      NOT NULL REFERENCES plantillas_cotizacion(id) ON DELETE RESTRICT,
    moneda            CHAR(3)      NOT NULL DEFAULT 'PEN' CHECK (moneda IN ('PEN','USD')),

    subtotal          dom_monto    NOT NULL DEFAULT 0,
    -- La tasa viaja con el documento: si el IGV cambia, las cotizaciones
    -- históricas siguen cuadrando con su propio cálculo.
    igv_tasa          NUMERIC(5,4) NOT NULL DEFAULT 0.1800 CHECK (igv_tasa BETWEEN 0 AND 1),
    igv               dom_monto    NOT NULL DEFAULT 0,
    descuento_tipo    dom_descuento_tipo,
    descuento_valor   NUMERIC(10,2) NOT NULL DEFAULT 0 CHECK (descuento_valor >= 0),
    descuento_monto   dom_monto    NOT NULL DEFAULT 0,
    descuento_razon   VARCHAR(300),
    total             dom_monto    NOT NULL DEFAULT 0,

    notas             TEXT,
    estado            dom_estado_cotizacion NOT NULL DEFAULT 'borrador',

    creado_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    creado_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    actualizado_por   INTEGER      REFERENCES usuarios(id) ON DELETE RESTRICT,
    actualizado_en    TIMESTAMPTZ,

    CONSTRAINT uq_cotizaciones_public_id UNIQUE (public_id),
    CONSTRAINT uq_cotizaciones_numero    UNIQUE (numero),   -- [MT] → (tenant_id, numero)
    -- Solo un borrador puede no tener número; todo lo emitido lo tiene.
    CONSTRAINT ck_cotizacion_numero_emitida CHECK (estado = 'borrador' OR numero IS NOT NULL),
    -- Aritmética verificada por la BD, no solo por la app.
    CONSTRAINT ck_cotizacion_igv     CHECK (igv = round(subtotal * igv_tasa, 2)),
    CONSTRAINT ck_cotizacion_total   CHECK (total = round(subtotal + igv - descuento_monto, 2)),
    CONSTRAINT ck_cotizacion_dcto    CHECK (descuento_monto <= round(subtotal + igv, 2)),
    CONSTRAINT ck_cotizacion_dcto_tipo CHECK (
        (descuento_tipo IS NULL     AND descuento_valor = 0 AND descuento_monto = 0) OR
        (descuento_tipo IS NOT NULL AND descuento_valor > 0)
    ),
    CONSTRAINT ck_cotizacion_dcto_pct CHECK (
        descuento_tipo <> 'porcentaje' OR descuento_valor <= 100
    )
);

-- [TENANT-SCOPED] Ítems: el SNAPSHOT del catálogo en el momento de cotizar.
-- Nada de esto se vuelve a leer en vivo desde ensayos_catalogo: si mañana
-- cambia el precio, la norma o la acreditación, la cotización emitida NO
-- cambia. Por eso hay columnas *_snapshot además de la FK al catálogo.
--
-- v3 agrega categoria_id + categoria_snapshot. Motivo real: las vistas del
-- dashboard de v2 hacían INNER JOIN por ensayo_id, así que cualquier ítem
-- cuyo ensayo desapareciera dejaba de sumar y el dashboard reportaba menos
-- dinero del cotizado. Con la categoría congelada en el ítem eso no ocurre.
CREATE TABLE cotizacion_items (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id         INTEGER      NOT NULL REFERENCES cotizaciones(id) ON DELETE CASCADE,
    orden                 SMALLINT     NOT NULL DEFAULT 0 CHECK (orden >= 0),
    -- Referencia al catálogo, solo informativa/analítica. El ensayo cotizado
    -- no se puede eliminar (trg_proteger_ensayo), así que no queda colgando.
    ensayo_id             INTEGER      REFERENCES ensayos_catalogo(id) ON DELETE RESTRICT,
    categoria_id          INTEGER      REFERENCES categorias_ensayo(id) ON DELETE RESTRICT,

    codigo_snapshot       VARCHAR(12)  NOT NULL CHECK (btrim(codigo_snapshot) <> ''),
    nombre_snapshot       VARCHAR(220) NOT NULL CHECK (btrim(nombre_snapshot) <> ''),
    norma_snapshot        VARCHAR(120),
    unidad_snapshot       dom_unidad   NOT NULL DEFAULT 'UND',
    categoria_snapshot    VARCHAR(40)  NOT NULL,
    subcategoria_snapshot VARCHAR(40),
    es_paquete_snapshot   BOOLEAN      NOT NULL DEFAULT FALSE,
    acreditado_snapshot   BOOLEAN      NOT NULL,
    -- TRUE si el usuario cambió la acreditación a mano en el paso "Resumen",
    -- distinto de lo que dice el catálogo maestro. Es un dato de auditoría:
    -- distingue "el catálogo decía esto" de "alguien lo forzó".
    acreditado_override   BOOLEAN      NOT NULL DEFAULT FALSE,

    cantidad              NUMERIC(8,2) NOT NULL DEFAULT 1 CHECK (cantidad > 0),
    precio_unitario       dom_precio   NOT NULL,
    subtotal              dom_monto    NOT NULL,
    -- Foto de lo que incluía el paquete ese día: [{codigo,nombre,norma,cantidad}].
    componentes_snapshot  JSONB,

    CONSTRAINT ck_item_subtotal CHECK (subtotal = round(cantidad * precio_unitario, 2)),
    CONSTRAINT ck_item_componentes CHECK (
        componentes_snapshot IS NULL OR jsonb_typeof(componentes_snapshot) = 'array'
    ),
    -- Un paquete siempre viaja con su composición congelada; un ensayo
    -- individual nunca la lleva.
    CONSTRAINT ck_item_paquete_con_componentes CHECK (
        (es_paquete_snapshot AND componentes_snapshot IS NOT NULL
             AND jsonb_array_length(componentes_snapshot) > 0)
        OR (NOT es_paquete_snapshot AND componentes_snapshot IS NULL)
    ),
    CONSTRAINT uq_item_orden UNIQUE (cotizacion_id, orden)
);

-- [TENANT-SCOPED] APPEND-ONLY. Línea de tiempo de estados; la escribe el
-- trigger de cotizaciones, no la aplicación, así no puede divergir del estado.
CREATE TABLE cotizacion_historial_estados (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cotizacion_id     INTEGER      NOT NULL REFERENCES cotizaciones(id) ON DELETE CASCADE,
    estado_anterior   dom_estado_cotizacion,
    estado            dom_estado_cotizacion NOT NULL,
    nota              VARCHAR(300),
    registrado_por    INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    registrado_en     TIMESTAMPTZ  NOT NULL DEFAULT now()
);


-- ----------------------------------------------------------------------------
-- 8. INTEGRACIONES DE NUBE Y DOCUMENTOS
-- ----------------------------------------------------------------------------
-- [TENANT-SCOPED] Una conexión a Google Drive / Microsoft 365.
--   titular = 'laboratorio' → la nube propia del laboratorio (empresa_id NULL)
--   titular = 'cliente'     → la nube del cliente (empresa_id obligatorio)
-- En v2 la integración era obligatoriamente de una empresa cliente, así que
-- una cotización de persona natural no podía tener documento. Corregido.
--
-- SEGURIDAD: access_token / refresh_token NUNCA viven en esta tabla.
-- token_ref es una referencia al secreto en un vault (AWS Secrets Manager,
-- GCP Secret Manager, Hashicorp Vault). La BD no guarda secretos.
CREATE TABLE integraciones (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    titular           VARCHAR(12)  NOT NULL CHECK (titular IN ('laboratorio','cliente')),
    empresa_id        INTEGER      REFERENCES empresas(id) ON DELETE RESTRICT,
    proveedor         dom_proveedor_nube NOT NULL,
    cuenta_email      dom_email,
    token_ref         VARCHAR(200),
    estado            dom_estado_integracion NOT NULL DEFAULT 'activa',
    conectado_por     INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    conectado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    revocado_en       TIMESTAMPTZ,
    CONSTRAINT uq_integraciones_public_id UNIQUE (public_id),
    CONSTRAINT ck_integracion_titular CHECK (
        (titular = 'cliente'     AND empresa_id IS NOT NULL) OR
        (titular = 'laboratorio' AND empresa_id IS NULL)
    ),
    CONSTRAINT ck_integracion_revocada CHECK (estado <> 'revocada' OR revocado_en IS NOT NULL),
    CONSTRAINT uq_integraciones_empresa_proveedor UNIQUE (empresa_id, proveedor)
);
-- Una sola integración propia por proveedor (empresa_id NULL no lo cubre el UNIQUE).
CREATE UNIQUE INDEX uq_integraciones_laboratorio
    ON integraciones (proveedor) WHERE empresa_id IS NULL;

-- [TENANT-SCOPED] Rastro de cada PDF/certificado emitido y de dónde quedó.
-- Sirve también como respuesta a "¿a qué nube salió este documento?".
CREATE TABLE documentos_externos (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id         UUID         NOT NULL DEFAULT gen_random_uuid(),
    cotizacion_id     INTEGER      NOT NULL REFERENCES cotizaciones(id) ON DELETE RESTRICT,
    origen            dom_origen_documento NOT NULL DEFAULT 'local',
    integracion_id    INTEGER      REFERENCES integraciones(id) ON DELETE RESTRICT,
    tipo_documento    dom_tipo_documento NOT NULL DEFAULT 'cotizacion_pdf',
    nombre_archivo    VARCHAR(200) NOT NULL CHECK (btrim(nombre_archivo) <> ''),
    url_externo       VARCHAR(500),
    hash_sha256       CHAR(64)     CHECK (hash_sha256 IS NULL OR hash_sha256 ~ '^[0-9a-f]{64}$'),
    subido_por        INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT,
    subido_en         TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_documentos_public_id UNIQUE (public_id),
    -- 'nube' exige integración y URL; 'local' no lleva ninguna de las dos.
    CONSTRAINT ck_documento_origen CHECK (
        (origen = 'nube'  AND integracion_id IS NOT NULL AND url_externo IS NOT NULL) OR
        (origen = 'local' AND integracion_id IS NULL)
    )
);


-- ----------------------------------------------------------------------------
-- 9. AUDITORÍA GENÉRICA
-- ----------------------------------------------------------------------------
-- [TENANT-SCOPED] APPEND-ONLY (ver 02_triggers.sql: no UPDATE nunca, y DELETE
-- solo a través de fn_purgar_auditoria, que deja su propia constancia).
--
-- Complementa creado_por / actualizado_por: aquí queda el detalle fino de qué
-- cambió, de qué valor a qué valor, quién y cuándo. Es lo primero que pide un
-- auditor ISO 17025 o una revisión legal.
--
-- registro_id es BIGINT porque audita también cotizacion_items (PK BIGINT).
-- usuario_id NO tiene fallback silencioso: lo resuelve fn_app_usuario(), que
-- lee app.usuario_id de la sesión. En v2 se leía la columna actualizado_por de
-- la propia fila, así que un UPDATE que no la fijara atribuía el cambio al
-- creador del registro — es decir, culpaba a la persona equivocada.
CREATE TABLE auditoria (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla              VARCHAR(60)  NOT NULL,
    registro_id        BIGINT       NOT NULL,
    registro_public_id UUID,                    -- si la tabla tiene public_id
    accion             dom_accion_auditoria NOT NULL,
    campos_cambiados   TEXT[],                  -- solo en UPDATE
    datos_anteriores   JSONB,
    datos_nuevos       JSONB,
    -- DEFERRABLE: la carga inicial inserta roles y el usuario "sistema" en la
    -- misma transacción, y el trigger de auditoría de `roles` se dispara antes
    -- de que exista el usuario 1. Fuera de ese caso la FK se verifica de
    -- inmediato (INITIALLY IMMEDIATE), así que no se relaja nada en operación.
    usuario_id         INTEGER      NOT NULL REFERENCES usuarios(id) ON DELETE RESTRICT
                                    DEFERRABLE INITIALLY IMMEDIATE,
    ip_origen          VARCHAR(45),
    registrado_en      TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT ck_auditoria_payload CHECK (
        (accion = 'INSERT' AND datos_anteriores IS NULL     AND datos_nuevos IS NOT NULL) OR
        (accion = 'UPDATE' AND datos_anteriores IS NOT NULL AND datos_nuevos IS NOT NULL) OR
        (accion = 'DELETE' AND datos_anteriores IS NOT NULL AND datos_nuevos IS NULL)
    )
);


-- ============================================================================
-- COMENTARIOS DE CATÁLOGO (los lee cualquier cliente SQL y pgAdmin)
-- ============================================================================
COMMENT ON TABLE schema_migrations IS 'GLOBAL. Versión del esquema desplegada.';
COMMENT ON TABLE roles            IS 'GLOBAL. Roles del producto.';
COMMENT ON TABLE usuarios         IS 'TENANT-SCOPED. Usuario id=1 (sistema) es global.';
COMMENT ON TABLE empresas         IS 'TENANT-SCOPED. Cartera de clientes del laboratorio.';
COMMENT ON TABLE contactos        IS 'TENANT-SCOPED. Personas de contacto de una empresa.';
COMMENT ON TABLE personas         IS 'TENANT-SCOPED. Cliente persona natural (DNI).';
COMMENT ON TABLE categorias_ensayo     IS 'TENANT-SCOPED. Catálogo nivel 1.';
COMMENT ON TABLE subcategorias_ensayo  IS 'TENANT-SCOPED. Catálogo nivel 2.';
COMMENT ON TABLE ensayos_catalogo      IS 'TENANT-SCOPED. Catálogo nivel 3: servicio vendible.';
COMMENT ON TABLE ensayo_acreditacion_historial IS 'TENANT-SCOPED. APPEND-ONLY. Vigencia ISO 17025.';
COMMENT ON TABLE paquete_componentes   IS 'TENANT-SCOPED. Composición de paquetes.';
COMMENT ON TABLE correlativos     IS 'TENANT-SCOPED. Contadores atómicos de códigos y números.';
COMMENT ON TABLE plantillas_cotizacion IS 'HÍBRIDA. 3 plantillas base del producto + las del tenant.';
COMMENT ON TABLE cotizaciones     IS 'TENANT-SCOPED. Documento comercial. No se elimina: se cancela.';
COMMENT ON TABLE cotizacion_items IS 'TENANT-SCOPED. Snapshot inmutable de lo cotizado.';
COMMENT ON TABLE cotizacion_historial_estados IS 'TENANT-SCOPED. APPEND-ONLY. Timeline de estados.';
COMMENT ON TABLE integraciones    IS 'TENANT-SCOPED. Conexión a nube. token_ref, nunca el token.';
COMMENT ON TABLE documentos_externos IS 'TENANT-SCOPED. Rastro de PDFs y certificados emitidos.';
COMMENT ON TABLE auditoria        IS 'TENANT-SCOPED. APPEND-ONLY. Quién cambió qué y cuándo.';

COMMENT ON COLUMN cotizaciones.public_id IS 'ID público opaco para URLs y QR. Nunca se expone el id serial.';
COMMENT ON COLUMN cotizaciones.numero    IS 'Código de negocio COT-YYYY-NNN. Lo emite la BD, no el frontend.';
COMMENT ON COLUMN usuarios.password_hash IS 'Solo hash Argon2id/bcrypt. Nunca contraseña ni token.';
COMMENT ON COLUMN integraciones.token_ref IS 'Referencia al secreto en el vault. La BD no guarda secretos.';

INSERT INTO schema_migrations (version, nombre, nota) VALUES
    ('0001', 'baseline v2 (esquema original)', 'Estado previo a la auditoría; ver migrations/0001_baseline_v2.sql'),
    ('0002', 'v3: IDs, correlativos, constraints, auditoría, snapshots', 'Este esquema');
