-- ============================================================================
--  ⚠  MIGRACIÓN 0003 — MULTI-TENANT ·  ESCRITA, **NO APLICADA**  ⚠
-- ============================================================================
-- ESTE ARCHIVO NO SE EJECUTA EN LA FASE ACTUAL.
--
-- Existe por una razón concreta: la decisión de cómo se aísla un tenant NO se
-- puede improvisar el día que llegue el segundo laboratorio. Si se improvisa,
-- se termina "agregando tenant_id" a las tablas y confiando en que cada
-- consulta del backend recuerde filtrarlo — que es exactamente el camino a una
-- fuga de datos entre clientes. Así que la decisión se toma ahora, se escribe
-- ahora, se revisa ahora, y se aplica cuando toque.
--
-- Precondiciones para aplicarla, TODAS:
--   1. La migración 0002 está aplicada y 99_verificacion.sql sale limpio.
--   2. Existe un backend que resuelve el tenant desde la SESIÓN AUTENTICADA
--      (nunca desde un parámetro, un header o el body del request).
--   3. Ese backend abre cada transacción con  SET LOCAL app.tenant_id = '<n>'.
--   4. Hay pruebas de aislamiento automatizadas (ver el skill /multi-tenant).
--   5. Hay respaldo verificado y ventana de mantenimiento.
--
-- Estado de esta migración: verificada sintácticamente y de extremo a extremo
-- sobre una copia desechable de la base (se aplica, los datos existentes
-- quedan en el tenant 1 y 99_verificacion.sql sigue limpio). La base del
-- proyecto NO la tiene aplicada.
--
-- Revisión de la fase 3C — lo que cambió respecto de la versión original:
--   · El RUC de GTQC ya no está escrito: se exige declararlo con
--     SET app.ruc_gtqc antes de aplicar, o la migración aborta (sección 1).
--   · auditoria.tenant_id admite NULL = cambio global del producto, y
--     fn_auditar() ya no llama a fn_app_tenant() (secciones 2 y 6).
--   · fn_max_plantillas_activas() cuenta por tenant; antes el cupo global
--     quedaba agotado por las 3 plantillas base y ningún laboratorio podía
--     crear las suyas (sección 6b).
--   · Las 8 vistas se recrean con security_invoker y exponen tenant_id
--     (sección 6c).
--
-- Lo que este archivo NO trae y es responsabilidad del backend:
--   · autenticación, JWT, sesiones, login;
--   · autorización por rol;
--   · resolución del tenant a partir del usuario;
--   · aislamiento en caché, colas, logs y almacenamiento de archivos.
--   La BD es la última línea de defensa, no la única.
-- ============================================================================

\echo '*** 0003 es una migración PREPARADA, no aplicada. Lea la cabecera. ***'
\set ON_ERROR_STOP on
BEGIN;

-- ----------------------------------------------------------------------------
-- 1. LA TABLA DE TENANTS
-- ----------------------------------------------------------------------------
-- [GLOBAL] Un tenant = un laboratorio cliente del SaaS. GTQC es el tenant 1.
CREATE TABLE tenants (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL DEFAULT gen_random_uuid(),
    slug            VARCHAR(40)  NOT NULL CHECK (slug ~ '^[a-z0-9-]{2,40}$'),
    razon_social    VARCHAR(200) NOT NULL,
    ruc             dom_ruc      NOT NULL,
    zona_horaria    VARCHAR(40)  NOT NULL DEFAULT 'America/Lima',
    plan            VARCHAR(20)  NOT NULL DEFAULT 'estandar',
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    suspendido_en   TIMESTAMPTZ,
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenants_public_id UNIQUE (public_id),
    CONSTRAINT uq_tenants_slug      UNIQUE (slug),
    CONSTRAINT uq_tenants_ruc       UNIQUE (ruc)
);
COMMENT ON TABLE tenants IS 'GLOBAL. Un laboratorio cliente del SaaS.';
-- zona_horaria por tenant: hoy fn_hoy_lima() fija America/Lima porque hay un
-- solo laboratorio. Con varios, la fecha de emisión debe salir de la zona del
-- tenant, no del servidor.

-- RUC de GTQC: CONFIRMADO por el Product Owner el 2026-09-28 (fase 3G).
--
-- La historia de este valor importa. La version original de esta migracion
-- traia '20601234567' sin respaldo en el repositorio, y el mockup usaba
-- '20500000001'. Ninguno de los dos estaba verificado, asi que la fase 3C
-- retiro el literal y obligo a declararlo con SET app.ruc_gtqc, para que un
-- RUC sin confirmar no pudiera colarse por descuido.
--
-- Ya esta confirmado, asi que el valor vuelve al archivo y la guarda se
-- retira: exigir un SET para un dato ya verificado solo anade friccion y un
-- modo de fallo nuevo el dia del despliegue.
--
-- `uq_tenants_ruc` es UNIQUE y el tenant 1 es el registro fundacional del
-- sistema: si este numero fuera incorrecto, apareceria impreso en cada
-- cotizacion que emita el laboratorio.
INSERT INTO tenants (id, slug, razon_social, ruc)
VALUES (1, 'gtqc', 'Group Total Quality Control S.A.C.', '20606918357');
SELECT setval(pg_get_serial_sequence('tenants','id'), 1);

-- Resolución del tenant activo. Sin contexto NO adivina: lanza error.
-- Es lo contrario de fn_app_usuario(), que sí tiene fallback: un cambio sin
-- autor identificado es un bug molesto; una consulta sin tenant identificado
-- es una fuga de datos entre clientes.
CREATE OR REPLACE FUNCTION fn_app_tenant() RETURNS INTEGER AS $$
DECLARE v INTEGER := NULLIF(current_setting('app.tenant_id', TRUE), '')::INTEGER;
BEGIN
    IF v IS NULL THEN
        RAISE EXCEPTION 'No hay tenant en el contexto de la sesión'
            USING ERRCODE = 'insufficient_privilege',
                  HINT = 'El backend debe ejecutar SET LOCAL app.tenant_id antes de cualquier consulta.';
    END IF;
    RETURN v;
END;
$$ LANGUAGE plpgsql STABLE;


-- ----------------------------------------------------------------------------
-- 2. tenant_id EN LAS TABLAS TENANT-SCOPED
-- ----------------------------------------------------------------------------
-- NO se agrega a ciegas. La clasificación razonada, tabla por tabla, está en
-- docs/AUDITORIA_BD_v3.md (sección "GLOBAL vs TENANT-SCOPED").
--
-- QUEDAN GLOBALES (sin tenant_id):
--   schema_migrations · tenants · roles
--   Motivo: son del producto. Los 4 roles son los mismos para todos; si un
--   laboratorio necesitara roles propios, se agregaría una tabla
--   roles_tenant aparte en vez de duplicar los básicos 1000 veces.
--
-- SON TENANT-SCOPED (llevan tenant_id):
--   usuarios, empresas, contactos, personas, categorias_ensayo,
--   subcategorias_ensayo, ensayos_catalogo, ensayo_acreditacion_historial,
--   paquete_componentes, correlativos, cotizaciones, cotizacion_items,
--   cotizacion_historial_estados, integraciones, documentos_externos, auditoria
--
-- ES HÍBRIDA:
--   plantillas_cotizacion — tenant_id NULL = plantilla base del producto,
--   visible para todos; tenant_id = N = plantilla propia de ese laboratorio.
--
-- Nota sobre las tablas HIJAS (cotizacion_items, paquete_componentes,
-- historiales): se les agrega tenant_id aunque sean alcanzables solo por su
-- padre. Razón: sin la columna, la política RLS de la hija tendría que hacer
-- un subquery al padre en cada fila leída, y un JOIN mal escrito en un reporte
-- se salta el aislamiento. Con la columna, la FK compuesta hace que sea
-- imposible que una hija pertenezca a otro tenant que su padre.

ALTER TABLE usuarios                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE empresas                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE contactos                     ADD COLUMN tenant_id INTEGER;
ALTER TABLE personas                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE categorias_ensayo             ADD COLUMN tenant_id INTEGER;
ALTER TABLE subcategorias_ensayo          ADD COLUMN tenant_id INTEGER;
ALTER TABLE ensayos_catalogo              ADD COLUMN tenant_id INTEGER;
ALTER TABLE ensayo_acreditacion_historial ADD COLUMN tenant_id INTEGER;
ALTER TABLE paquete_componentes           ADD COLUMN tenant_id INTEGER;
ALTER TABLE correlativos                  ADD COLUMN tenant_id INTEGER;
ALTER TABLE plantillas_cotizacion         ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizaciones                  ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizacion_items              ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizacion_historial_estados  ADD COLUMN tenant_id INTEGER;
ALTER TABLE integraciones                 ADD COLUMN tenant_id INTEGER;
ALTER TABLE documentos_externos           ADD COLUMN tenant_id INTEGER;
ALTER TABLE auditoria                     ADD COLUMN tenant_id INTEGER;

-- Todo lo existente es del tenant 1 (GTQC).
--
-- El relleno necesita desactivar los triggers de usuario mientras dura: las
-- tablas append-only (auditoria, los dos historiales) rechazan cualquier
-- UPDATE, y a_congelar rechaza tocar una cotización ya emitida. Eso es
-- justamente lo que deben hacer en operación normal; aquí se apagan de forma
-- explícita y acotada, y se vuelven a encender antes de terminar. Las FK
-- siguen activas: DISABLE TRIGGER USER no toca los triggers del sistema.
DO $apagar$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'usuarios','empresas','contactos','personas','categorias_ensayo',
        'subcategorias_ensayo','ensayos_catalogo','ensayo_acreditacion_historial',
        'paquete_componentes','plantillas_cotizacion','cotizaciones','cotizacion_items',
        'cotizacion_historial_estados','integraciones','documentos_externos','auditoria']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I DISABLE TRIGGER USER', r.t);
    END LOOP;
END
$apagar$;

UPDATE usuarios                      SET tenant_id = 1;
UPDATE empresas                      SET tenant_id = 1;
UPDATE contactos                     SET tenant_id = 1;
UPDATE personas                      SET tenant_id = 1;
UPDATE categorias_ensayo             SET tenant_id = 1;
UPDATE subcategorias_ensayo          SET tenant_id = 1;
UPDATE ensayos_catalogo              SET tenant_id = 1;
UPDATE ensayo_acreditacion_historial SET tenant_id = 1;
UPDATE paquete_componentes           SET tenant_id = 1;
UPDATE correlativos                  SET tenant_id = 1;
UPDATE cotizaciones                  SET tenant_id = 1;
UPDATE cotizacion_items              SET tenant_id = 1;
UPDATE cotizacion_historial_estados  SET tenant_id = 1;
UPDATE integraciones                 SET tenant_id = 1;
UPDATE documentos_externos           SET tenant_id = 1;
UPDATE auditoria                     SET tenant_id = 1;
-- Las 3 plantillas base pasan a ser del producto (tenant_id NULL), visibles
-- para todos los laboratorios; las que cree cada uno llevarán su tenant_id.
UPDATE plantillas_cotizacion SET tenant_id = NULL WHERE slug IN ('estandar','premium','express');

-- El usuario "sistema" (id = 1) es el único usuario global: es el autor de los
-- seeds y el fallback de auditoría de TODOS los tenants.
UPDATE usuarios SET tenant_id = NULL WHERE id = 1;

-- Triggers de vuelta. A partir de aquí la base protege igual que antes.
DO $encender$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'usuarios','empresas','contactos','personas','categorias_ensayo',
        'subcategorias_ensayo','ensayos_catalogo','ensayo_acreditacion_historial',
        'paquete_componentes','plantillas_cotizacion','cotizaciones','cotizacion_items',
        'cotizacion_historial_estados','integraciones','documentos_externos','auditoria']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE TRIGGER USER', r.t);
    END LOOP;
END
$encender$;

DO $obligatorio$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'empresas','contactos','personas','categorias_ensayo','subcategorias_ensayo',
        'ensayos_catalogo','ensayo_acreditacion_historial','paquete_componentes',
        'correlativos','cotizaciones','cotizacion_items','cotizacion_historial_estados',
        'integraciones','documentos_externos']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I ALTER COLUMN tenant_id SET NOT NULL', r.t);
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (tenant_id)
                        REFERENCES tenants(id) ON DELETE RESTRICT',
                       r.t, 'fk_' || r.t || '_tenant');
        EXECUTE format('ALTER TABLE %I ALTER COLUMN tenant_id SET DEFAULT fn_app_tenant()', r.t);
    END LOOP;
END
$obligatorio$;

-- usuarios, plantillas_cotizacion y auditoria admiten NULL (fila global).
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE plantillas_cotizacion ADD CONSTRAINT fk_plantillas_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;

-- Admitir NULL no es lo mismo que ponerlo por omisión.
--
-- Estas dos tablas quedan fuera del bucle de arriba porque su tenant_id puede
-- ser NULL, pero eso las dejaba también sin DEFAULT, y el efecto era una fuga
-- silenciosa: un laboratorio que creara una plantilla propia sin nombrar el
-- tenant obtenía tenant_id NULL, es decir, una PLANTILLA BASE DEL PRODUCTO
-- visible para todos los demás laboratorios. Lo detectó la prueba 15 de
-- 97_aislamiento.sql, que esperaba un bloqueo y vio pasar la operación: el
-- trigger a_validar_plantilla hacía lo correcto, pero la plantilla ya no era
-- ajena, se había vuelto global.
-- En usuarios el efecto es equivalente: un alta sin tenant explícito crearía
-- otro usuario global como el usuario sistema.
--
-- Con el DEFAULT, lo propio es lo que ocurre por omisión y lo global exige
-- escribir tenant_id = NULL a mano. Crear algo que verán todos los clientes
-- debe ser un acto deliberado, nunca un descuido.
ALTER TABLE usuarios              ALTER COLUMN tenant_id SET DEFAULT fn_app_tenant();
ALTER TABLE plantillas_cotizacion ALTER COLUMN tenant_id SET DEFAULT fn_app_tenant();

-- auditoria.tenant_id ADMITE NULL, y ese NULL significa algo concreto:
-- "este cambio no pertenece a ningún laboratorio, es del producto".
--
-- Ocurre de verdad, no es un caso teórico: cambiar un rol, editar una
-- plantilla base o tocar al usuario `sistema` son filas globales. Forzando
-- NOT NULL habría que atribuirlas al tenant que estuviera en la sesión, y el
-- rastro diría que el laboratorio A modificó algo que es de todos.
--
-- Tampoco lleva DEFAULT fn_app_tenant(): el valor lo pone siempre fn_auditar()
-- a partir de la fila auditada. Un DEFAULT que lanza excepción en una tabla
-- append-only sería una trampa esperando a que alguien inserte a mano.
--
-- La futura política RLS (0004) es, en consecuencia, la de una tabla híbrida:
--     USING (tenant_id IS NULL OR tenant_id = fn_app_tenant())
-- Cada laboratorio ve su rastro y el de los cambios del producto que le
-- afectan; el del vecino, nunca.
ALTER TABLE auditoria ADD CONSTRAINT fk_auditoria_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
COMMENT ON COLUMN auditoria.tenant_id IS
    'NULL = cambio global del producto (roles, plantillas base, usuario sistema).';


-- ----------------------------------------------------------------------------
-- 3. UNICIDAD: DE GLOBAL A "POR TENANT"
-- ----------------------------------------------------------------------------
-- Esto es lo que más se olvida y lo que más duele. Si `ruc` sigue siendo único
-- global, el segundo laboratorio no puede registrar a un cliente que el primero
-- ya tenía. Si `codigo` sigue siendo único global, dos laboratorios no pueden
-- tener ambos su SU-01. Y si `numero` sigue siendo único global, el segundo
-- laboratorio empieza a numerar en COT-2026-203.
ALTER TABLE empresas DROP CONSTRAINT uq_empresas_ruc;
ALTER TABLE empresas ADD  CONSTRAINT uq_empresas_ruc UNIQUE (tenant_id, ruc);

ALTER TABLE personas DROP CONSTRAINT uq_personas_dni;
ALTER TABLE personas ADD  CONSTRAINT uq_personas_dni UNIQUE (tenant_id, dni);

ALTER TABLE contactos DROP CONSTRAINT uq_contactos_empresa_dni;
ALTER TABLE contactos ADD  CONSTRAINT uq_contactos_empresa_dni UNIQUE (tenant_id, empresa_id, dni);

ALTER TABLE categorias_ensayo DROP CONSTRAINT uq_categorias_slug;
ALTER TABLE categorias_ensayo ADD  CONSTRAINT uq_categorias_slug UNIQUE (tenant_id, slug);
ALTER TABLE categorias_ensayo DROP CONSTRAINT uq_categorias_prefijo;
ALTER TABLE categorias_ensayo ADD  CONSTRAINT uq_categorias_prefijo UNIQUE (tenant_id, prefijo_codigo);
DROP INDEX uq_categorias_nombre;
CREATE UNIQUE INDEX uq_categorias_nombre ON categorias_ensayo (tenant_id, lower(nombre));

DROP INDEX uq_subcategorias_nombre;
CREATE UNIQUE INDEX uq_subcategorias_nombre
    ON subcategorias_ensayo (tenant_id, categoria_id, lower(nombre));

ALTER TABLE ensayos_catalogo DROP CONSTRAINT uq_ensayos_codigo;
ALTER TABLE ensayos_catalogo ADD  CONSTRAINT uq_ensayos_codigo UNIQUE (tenant_id, codigo);

ALTER TABLE cotizaciones DROP CONSTRAINT uq_cotizaciones_numero;
ALTER TABLE cotizaciones ADD  CONSTRAINT uq_cotizaciones_numero UNIQUE (tenant_id, numero);

ALTER TABLE plantillas_cotizacion DROP CONSTRAINT uq_plantillas_slug;
CREATE UNIQUE INDEX uq_plantillas_slug_tenant ON plantillas_cotizacion (tenant_id, slug)
    WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_plantillas_slug_base   ON plantillas_cotizacion (slug)
    WHERE tenant_id IS NULL;

-- El NULL de usuarios.tenant_id queda RESERVADO, no abierto.
--
-- Esta migración le da un significado nuevo a `tenant_id IS NULL` en usuarios:
-- "usuario global del producto". Hoy eso describe a exactamente una fila, el
-- usuario `sistema` (id 1), que es autor de los seeds y fallback de auditoría.
--
-- El problema es que crear la semántica sin acotarla deja abierta una vía de
-- escalada: bajo la política RLS híbrida prevista para 0004
--     USING (tenant_id IS NULL OR tenant_id = fn_app_tenant())
-- un usuario con tenant_id NULL es visible desde TODOS los laboratorios. Un
-- alta con ese valor crea, de hecho, una identidad de alcance global.
--
-- La vía accidental ya está cerrada: usuarios.tenant_id tiene DEFAULT
-- fn_app_tenant(), así que un alta sin tenant explícito queda en el tenant de
-- la sesión. Este índice cierra la vía deliberada.
--
-- Cuando exista el Super Admin (ver docs/SEGURIDAD_RBAC.md §4), su migración
-- relajará este índice de forma explícita y revisable, junto con roles.scope y
-- la tabla de concesiones de plataforma. Esa es justamente la intención: que
-- añadir una identidad de alcance global sea un cambio de esquema que alguien
-- tenga que revisar, y no un INSERT.
CREATE UNIQUE INDEX uq_usuarios_global ON usuarios ((TRUE)) WHERE tenant_id IS NULL;
COMMENT ON INDEX uq_usuarios_global IS
    'Reserva el tenant_id NULL para un único usuario global (sistema). Relajar solo al introducir el Super Admin.';

DROP INDEX uq_usuarios_email;
-- El email sí sigue siendo único en TODO el sistema: una persona = una cuenta.
-- Si mañana la misma persona trabaja para dos laboratorios, se resuelve con
-- una tabla usuario_tenant (pertenencia N:N), no duplicando la identidad.
CREATE UNIQUE INDEX uq_usuarios_email ON usuarios (lower(email));

DROP INDEX uq_integraciones_laboratorio;
CREATE UNIQUE INDEX uq_integraciones_laboratorio
    ON integraciones (tenant_id, proveedor) WHERE empresa_id IS NULL;
ALTER TABLE integraciones DROP CONSTRAINT uq_integraciones_empresa_proveedor;
ALTER TABLE integraciones ADD  CONSTRAINT uq_integraciones_empresa_proveedor
    UNIQUE (tenant_id, empresa_id, proveedor);

-- Correlativos: la PK incluye el tenant, y con eso Tenant A y Tenant B pueden
-- tener ambos su COT-2026-001 y su propio SU-29 sin saber el uno del otro.
ALTER TABLE correlativos DROP CONSTRAINT correlativos_pkey;
ALTER TABLE correlativos ADD  CONSTRAINT correlativos_pkey
    PRIMARY KEY (tenant_id, ambito, clave, periodo);


-- ----------------------------------------------------------------------------
-- 4. FK COMPUESTAS: QUE LA BASE HAGA IMPOSIBLE EL CRUCE DE TENANTS
-- ----------------------------------------------------------------------------
-- Agregar tenant_id NO aísla nada por sí solo. Sin esto, una cotización del
-- Tenant A puede apuntar tranquilamente a una empresa del Tenant B: cada fila
-- cumple su propia FK y su propio tenant_id, y el resultado es una fuga.
--
-- El patrón: la tabla padre declara UNIQUE (tenant_id, id) y la hija referencia
-- ese par. Entonces la pertenencia al mismo tenant no es una regla que el
-- backend deba recordar: es una imposibilidad física en el motor.
-- Es exactamente el mismo mecanismo que v3 ya usa hoy para
-- (empresa_id, contacto_id) y para (categoria_id, subcategoria_id) — por eso
-- esta migración es mecánica y no un rediseño.

ALTER TABLE tenants                  ADD CONSTRAINT uq_tenants_tid           UNIQUE (id);
ALTER TABLE empresas                 ADD CONSTRAINT uq_empresas_tenant_id    UNIQUE (tenant_id, id);
ALTER TABLE contactos                ADD CONSTRAINT uq_contactos_tenant_id   UNIQUE (tenant_id, id);
ALTER TABLE personas                 ADD CONSTRAINT uq_personas_tenant_id    UNIQUE (tenant_id, id);
ALTER TABLE categorias_ensayo        ADD CONSTRAINT uq_categorias_tenant_id  UNIQUE (tenant_id, id);
ALTER TABLE subcategorias_ensayo     ADD CONSTRAINT uq_subcat_tenant_id      UNIQUE (tenant_id, id);
ALTER TABLE ensayos_catalogo         ADD CONSTRAINT uq_ensayos_tenant_id     UNIQUE (tenant_id, id);
ALTER TABLE cotizaciones             ADD CONSTRAINT uq_cotizaciones_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE integraciones            ADD CONSTRAINT uq_integraciones_tenant_id UNIQUE (tenant_id, id);

-- contactos → empresas (mismo tenant)
ALTER TABLE contactos DROP CONSTRAINT contactos_empresa_id_fkey;
ALTER TABLE contactos ADD  CONSTRAINT contactos_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;

-- subcategorias → categorias (mismo tenant)
ALTER TABLE subcategorias_ensayo DROP CONSTRAINT subcategorias_ensayo_categoria_id_fkey;
ALTER TABLE subcategorias_ensayo ADD  CONSTRAINT subcategorias_ensayo_categoria_id_fkey
    FOREIGN KEY (tenant_id, categoria_id) REFERENCES categorias_ensayo (tenant_id, id) ON DELETE RESTRICT;

-- ensayos → subcategorias (mismo tenant Y misma categoría: FK de 3 columnas).
-- Primero cae la FK que cuelga del UNIQUE, después el UNIQUE: al revés,
-- PostgreSQL rechaza el DROP por dependencia.
ALTER TABLE ensayos_catalogo     DROP CONSTRAINT fk_ensayos_subcategoria;
ALTER TABLE subcategorias_ensayo DROP CONSTRAINT uq_subcategorias_categoria_id;
ALTER TABLE subcategorias_ensayo ADD  CONSTRAINT uq_subcategorias_categoria_id
    UNIQUE (tenant_id, categoria_id, id);
ALTER TABLE ensayos_catalogo ADD  CONSTRAINT fk_ensayos_subcategoria
    FOREIGN KEY (tenant_id, categoria_id, subcategoria_id)
    REFERENCES subcategorias_ensayo (tenant_id, categoria_id, id) ON DELETE RESTRICT;

-- acreditación e componentes → ensayos (mismo tenant)
ALTER TABLE ensayo_acreditacion_historial DROP CONSTRAINT ensayo_acreditacion_historial_ensayo_id_fkey;
ALTER TABLE ensayo_acreditacion_historial ADD  CONSTRAINT ensayo_acreditacion_historial_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE paquete_componentes DROP CONSTRAINT paquete_componentes_ensayo_id_fkey;
ALTER TABLE paquete_componentes ADD  CONSTRAINT paquete_componentes_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE paquete_componentes DROP CONSTRAINT paquete_componentes_ensayo_componente_id_fkey;
ALTER TABLE paquete_componentes ADD  CONSTRAINT paquete_componentes_ensayo_componente_id_fkey
    FOREIGN KEY (tenant_id, ensayo_componente_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE RESTRICT;

-- cotizaciones → cliente (mismo tenant). El contacto sigue amarrado además a
-- su empresa: la FK pasa a ser (tenant_id, empresa_id, contacto_id).
ALTER TABLE cotizaciones DROP CONSTRAINT cotizaciones_empresa_id_fkey;
ALTER TABLE cotizaciones ADD  CONSTRAINT cotizaciones_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizaciones DROP CONSTRAINT cotizaciones_persona_id_fkey;
ALTER TABLE cotizaciones ADD  CONSTRAINT cotizaciones_persona_id_fkey
    FOREIGN KEY (tenant_id, persona_id) REFERENCES personas (tenant_id, id) ON DELETE RESTRICT;
-- Igual que arriba: la FK primero, el UNIQUE del que depende después.
ALTER TABLE cotizaciones DROP CONSTRAINT fk_cotizacion_contacto_de_su_empresa;
ALTER TABLE contactos    DROP CONSTRAINT uq_contactos_empresa_id;
ALTER TABLE contactos    ADD  CONSTRAINT uq_contactos_empresa_id UNIQUE (tenant_id, empresa_id, id);
ALTER TABLE cotizaciones ADD  CONSTRAINT fk_cotizacion_contacto_de_su_empresa
    FOREIGN KEY (tenant_id, empresa_id, contacto_id)
    REFERENCES contactos (tenant_id, empresa_id, id) ON DELETE RESTRICT;

-- ítems, historial y documentos → cotización (mismo tenant)
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_cotizacion_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_ensayo_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_categoria_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_categoria_id_fkey
    FOREIGN KEY (tenant_id, categoria_id) REFERENCES categorias_ensayo (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizacion_historial_estados DROP CONSTRAINT cotizacion_historial_estados_cotizacion_id_fkey;
ALTER TABLE cotizacion_historial_estados ADD  CONSTRAINT cotizacion_historial_estados_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE documentos_externos DROP CONSTRAINT documentos_externos_cotizacion_id_fkey;
ALTER TABLE documentos_externos ADD  CONSTRAINT documentos_externos_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE documentos_externos DROP CONSTRAINT documentos_externos_integracion_id_fkey;
ALTER TABLE documentos_externos ADD  CONSTRAINT documentos_externos_integracion_id_fkey
    FOREIGN KEY (tenant_id, integracion_id) REFERENCES integraciones (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE integraciones DROP CONSTRAINT integraciones_empresa_id_fkey;
ALTER TABLE integraciones ADD  CONSTRAINT integraciones_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;

-- La plantilla de una cotización: o es base del producto, o es del mismo
-- tenant. Un CHECK de fila no puede mirar otra tabla, así que va por trigger.
CREATE OR REPLACE FUNCTION fn_validar_plantilla_tenant() RETURNS TRIGGER AS $$
DECLARE v_tp INTEGER;
BEGIN
    SELECT tenant_id INTO v_tp FROM plantillas_cotizacion WHERE id = NEW.plantilla_id;
    IF v_tp IS NOT NULL AND v_tp <> NEW.tenant_id THEN
        RAISE EXCEPTION 'La plantilla % pertenece a otro tenant', NEW.plantilla_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER a_validar_plantilla BEFORE INSERT OR UPDATE OF plantilla_id, tenant_id ON cotizaciones
    FOR EACH ROW EXECUTE FUNCTION fn_validar_plantilla_tenant();


-- ----------------------------------------------------------------------------
-- 5. ÍNDICES CON EL TENANT AL FRENTE
-- ----------------------------------------------------------------------------
-- Toda consulta del sistema llevará WHERE tenant_id = N. Un índice que no
-- empiece por tenant_id obliga a filtrar después de leer, y el rendimiento se
-- degrada con cada laboratorio nuevo.
DROP INDEX idx_cotizaciones_fecha;
CREATE INDEX idx_cotizaciones_fecha ON cotizaciones (tenant_id, fecha_emision)
    WHERE estado <> 'borrador';
DROP INDEX idx_cotizaciones_estado_fecha;
CREATE INDEX idx_cotizaciones_estado_fecha ON cotizaciones (tenant_id, estado, fecha_emision DESC);
DROP INDEX idx_catalogo_navegacion;
CREATE INDEX idx_catalogo_navegacion
    ON ensayos_catalogo (tenant_id, categoria_id, subcategoria_id, codigo) WHERE activo;
DROP INDEX idx_auditoria_registro;
CREATE INDEX idx_auditoria_registro ON auditoria (tenant_id, tabla, registro_id);
DROP INDEX idx_auditoria_fecha;
CREATE INDEX idx_auditoria_fecha ON auditoria (tenant_id, registrado_en DESC);
CREATE INDEX idx_items_tenant_categoria ON cotizacion_items (tenant_id, categoria_id);

-- Las tablas hijas cuyo tenant_id quedó sin índice líder: lo necesitan tanto
-- para la FK a tenants como para que la futura política RLS filtre por índice
-- en lugar de leer la tabla completa. Las demás ya están cubiertas por su
-- UNIQUE (tenant_id, …) o por los índices compuestos de arriba.
CREATE INDEX idx_usuarios_tenant       ON usuarios (tenant_id);
CREATE INDEX idx_acreditacion_tenant   ON ensayo_acreditacion_historial (tenant_id, ensayo_id);
CREATE INDEX idx_componentes_tenant    ON paquete_componentes (tenant_id, ensayo_id);
CREATE INDEX idx_hist_estados_tenant   ON cotizacion_historial_estados (tenant_id, cotizacion_id);
CREATE INDEX idx_documentos_tenant     ON documentos_externos (tenant_id, cotizacion_id);


-- ----------------------------------------------------------------------------
-- 6. FUNCIONES CONSCIENTES DEL TENANT
-- ----------------------------------------------------------------------------
-- El correlativo se vuelve por tenant. Nada más cambia en su lógica: sigue
-- siendo un INSERT ... ON CONFLICT DO UPDATE atómico.
CREATE OR REPLACE FUNCTION fn_siguiente_correlativo(
    p_ambito VARCHAR, p_clave VARCHAR, p_periodo VARCHAR
) RETURNS INTEGER AS $$
DECLARE v_valor INTEGER;
BEGIN
    INSERT INTO correlativos (tenant_id, ambito, clave, periodo, ultimo)
    VALUES (fn_app_tenant(), p_ambito, p_clave, p_periodo, 1)
    ON CONFLICT (tenant_id, ambito, clave, periodo)
    DO UPDATE SET ultimo = correlativos.ultimo + 1, actualizado_en = now()
    RETURNING ultimo INTO v_valor;
    RETURN v_valor;
END;
$$ LANGUAGE plpgsql;

-- La fecha de negocio sale de la zona horaria DEL TENANT, no del servidor.
CREATE OR REPLACE FUNCTION fn_hoy_lima() RETURNS DATE AS $$
    SELECT (now() AT TIME ZONE COALESCE(
        (SELECT zona_horaria FROM tenants WHERE id = fn_app_tenant()), 'America/Lima'))::date;
$$ LANGUAGE sql STABLE;
COMMENT ON FUNCTION fn_hoy_lima() IS
    'Conserva el nombre por compatibilidad; ahora resuelve la zona del tenant.';

-- El validador del prefijo del código debe mirar la categoría DEL MISMO tenant.
CREATE OR REPLACE FUNCTION fn_validar_codigo_ensayo() RETURNS TRIGGER AS $$
DECLARE v_prefijo VARCHAR(3);
BEGIN
    SELECT prefijo_codigo INTO v_prefijo FROM categorias_ensayo
     WHERE id = NEW.categoria_id AND tenant_id = NEW.tenant_id;
    IF v_prefijo IS NULL THEN
        RAISE EXCEPTION 'La categoría % no existe en este tenant', NEW.categoria_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    IF NEW.codigo !~ ('^' || v_prefijo || '-[0-9]{2,4}$') THEN
        RAISE EXCEPTION 'El código "%" no corresponde a la categoría (debe ser %-NN)', NEW.codigo, v_prefijo
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ----------------------------------------------------------------------------
-- 6d. CAMPOS SENSIBLES: LA AUDITORIA NUNCA ARCHIVA UN SECRETO
-- ----------------------------------------------------------------------------
-- fn_auditar() guarda la fila entera con to_jsonb(NEW). Eso significa que, en
-- cuanto usuarios.password_hash deje de ser NULL, CADA cambio de contrasena
-- copiaria el hash a `auditoria` -- que es append-only y no se puede limpiar.
-- Quien consiguiera leer la auditoria obtendria material para un ataque
-- offline, incluidas contrasenas ya rotadas.
--
-- Se verifico ejecutandolo sobre una copia desechable: el hash quedaba en
-- auditoria.datos_nuevos->>'password_hash' en claro.
--
-- Se corrige aqui, y no mas adelante, por dos razones:
--   · esta migracion YA reemplaza fn_auditar(); cualquier otra ubicacion
--     obligaria a reescribir la misma funcion dos veces;
--   · el dano es irreversible: una vez el hash entra en una tabla append-only,
--     no sale.
--
-- No es un parche para password_hash: es un catalogo. Anadir un campo sensible
-- nuevo (mfa_secret, refresh_token_hash, token_recuperacion) es un INSERT, no
-- un cambio de funcion.
CREATE TABLE campos_sensibles (
    id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tabla   VARCHAR(63)  NOT NULL,
    columna VARCHAR(63)  NOT NULL,
    motivo  VARCHAR(200) NOT NULL,
    CONSTRAINT uq_campos_sensibles       UNIQUE (tabla, columna),
    CONSTRAINT ck_campos_sensibles_motivo CHECK (btrim(motivo) <> '')
);
COMMENT ON TABLE campos_sensibles IS
    'GLOBAL. Columnas que la auditoria registra como CAMBIADAS pero cuyo valor NUNCA almacena.';
-- La PK es un id propio y no (tabla, columna) porque auditoria.registro_id es
-- NOT NULL: sin una columna `id`, esta tabla no podria auditarse a si misma.
-- Y debe poder: quitar una proteccion tiene que dejar rastro.

INSERT INTO campos_sensibles (tabla, columna, motivo) VALUES
    ('usuarios', 'password_hash',
     'Hash de contrasena. La auditoria es append-only: lo que entra no se puede borrar.');

CREATE OR REPLACE FUNCTION fn_campos_sensibles(p_tabla TEXT) RETURNS TEXT[] AS $$
    SELECT COALESCE(array_agg(columna), ARRAY[]::TEXT[])
      FROM campos_sensibles WHERE tabla = p_tabla;
$$ LANGUAGE sql STABLE;
COMMENT ON FUNCTION fn_campos_sensibles(TEXT) IS
    'STABLE para que PostgreSQL la evalue una vez por sentencia y no una vez por fila.';

CREATE OR REPLACE FUNCTION fn_redactar(p_datos JSONB, p_cols TEXT[]) RETURNS JSONB AS $$
DECLARE v_col TEXT;
BEGIN
    IF p_datos IS NULL THEN RETURN NULL; END IF;
    FOREACH v_col IN ARRAY p_cols LOOP
        -- Un NULL se deja como NULL: sustituirlo por '[REDACTADO]' insinuaria
        -- que habia un secreto donde no lo habia, y "no tenia contrasena" es
        -- un hecho de auditoria legitimo y no confidencial.
        IF p_datos ? v_col AND jsonb_typeof(p_datos -> v_col) <> 'null' THEN
            p_datos := jsonb_set(p_datos, ARRAY[v_col], '"[REDACTADO]"'::jsonb);
        END IF;
    END LOOP;
    RETURN p_datos;
END;
$$ LANGUAGE plpgsql IMMUTABLE;


-- La auditoría se sella con el tenant DE LA FILA AUDITADA, y con nada más.
--
-- No lleva COALESCE(..., fn_app_tenant()). Dos razones:
--   · Las tablas tenant-scoped tienen tenant_id NOT NULL, así que la fila
--     SIEMPRE lo trae: el COALESCE nunca haría falta para ellas.
--   · Las globales (roles, plantillas base, usuario sistema) no lo traen, y ahí
--     el COALESCE hacía justo lo contrario de lo correcto: llamaba a
--     fn_app_tenant(), que lanza excepción si no hay contexto. Un superadmin
--     modificando un rol del producto no puede aplicar la migración ni tocar
--     un rol sin inventarse un tenant al que no pertenece.
-- Sin el COALESCE, una fila sin tenant_id produce una fila de auditoría con
-- tenant_id NULL, que es exactamente lo que significa: cambio global.
CREATE OR REPLACE FUNCTION fn_auditar() RETURNS TRIGGER AS $$
DECLARE
    v_new JSONB := CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END;
    v_old JSONB := CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END;
    v_ref JSONB := COALESCE(v_new, v_old);
    v_campos TEXT[];
    v_sens   TEXT[];
BEGIN
    -- PASO 1 - los campos cambiados se calculan con los VALORES REALES.
    IF TG_OP = 'UPDATE' THEN
        SELECT array_agg(k ORDER BY k) INTO v_campos
        FROM jsonb_object_keys(v_new) AS k
        WHERE v_old -> k IS DISTINCT FROM v_new -> k;
        IF v_campos IS NULL OR v_campos <@ ARRAY['actualizado_en','actualizado_por'] THEN
            RETURN NULL;
        END IF;
    END IF;

    -- PASO 2 - y SOLO DESPUES se redactan los valores sensibles.
    --
    -- El orden es la parte que se puede equivocar, y equivocarlo cuesta caro:
    -- redactando primero, los dos valores pasarian a ser '[REDACTADO]', serian
    -- iguales, el campo no figuraria como cambiado y -por la salida anticipada
    -- de arriba- un cambio de contrasena podria no generar NINGUNA fila de
    -- auditoria. Se perderia el secreto y ademas la trazabilidad.
    v_sens := fn_campos_sensibles(TG_TABLE_NAME);
    IF array_length(v_sens, 1) IS NOT NULL THEN
        v_new := fn_redactar(v_new, v_sens);
        v_old := fn_redactar(v_old, v_sens);
    END IF;

    INSERT INTO auditoria (tenant_id, tabla, registro_id, registro_public_id, accion,
                           campos_cambiados, datos_anteriores, datos_nuevos, usuario_id, ip_origen)
    VALUES ((v_ref->>'tenant_id')::INTEGER,
            TG_TABLE_NAME, (v_ref->>'id')::BIGINT,
            NULLIF(v_ref->>'public_id','')::UUID, TG_OP, v_campos, v_old, v_new,
            fn_app_usuario(), fn_app_ip());
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ----------------------------------------------------------------------------
-- 6b. EL LÍMITE DE PLANTILLAS PASA A SER POR TENANT  (defecto F-2)
-- ----------------------------------------------------------------------------
-- fn_max_plantillas_activas() cuenta hoy TODAS las plantillas activas de la
-- base, sin mirar de quién son:
--
--     IF NEW.activo AND (SELECT COUNT(*) FROM plantillas_cotizacion
--                         WHERE activo AND id <> COALESCE(NEW.id, -1)) >= 3
--
-- Con un solo laboratorio da igual. Con varios rompe dos cosas a la vez:
--   · las 3 plantillas base del producto quedan activas tras esta migración,
--     así que el cupo global ya está agotado y NINGÚN laboratorio podría crear
--     una plantilla propia — la función quedaría muerta al nacer;
--   · y si pudieran, el laboratorio A le consumiría cupo al B.
--
-- QUÉ SIGNIFICA "MÁXIMO 3" — evidencia, no suposición:
--   · el trigger dice "el mismo límite que aplica la app";
--   · en el mockup, MAX_PLANTILLAS = 3 se compara contra DB.plantillas, que es
--     la lista PROPIA del laboratorio (arranca como copia de las 3 base y el
--     usuario las edita y las elimina);
--   · COMMENT ON TABLE dice "3 plantillas base del producto + las del tenant",
--     y ese "+" describe dos conjuntos distintos que se suman.
--
-- AMBIGÜEDAD QUE QUEDA ABIERTA — decisión de producto, no de desarrollo:
--   El mockup trata las 3 plantillas como propias y editables del laboratorio;
--   esta migración las convierte en base del producto, compartidas y de solo
--   lectura. Son dos modelos distintos, y como el mockup está congelado la
--   contradicción no se resuelve leyendo el código.
--   Lo que NO es ambiguo es que el límite debe ser POR TENANT: ninguna lectura
--   admite que un laboratorio consuma el cupo de otro. Eso es lo que se corrige.
--   Lo que SÍ queda por confirmar es si las 3 base cuentan dentro del cupo de
--   cada laboratorio. Se implementa que NO cuenten, porque bajo la otra lectura
--   el cupo nace agotado y crear plantillas sería inalcanzable: una regla que
--   hace imposible su propia funcionalidad no puede ser la buscada. Si producto
--   decide lo contrario, el cambio es quitar el retorno anticipado de abajo y
--   contar también las filas con tenant_id IS NULL.
CREATE OR REPLACE FUNCTION fn_max_plantillas_activas() RETURNS TRIGGER AS $$
BEGIN
    -- Las plantillas base del producto (tenant_id NULL) no pasan por el cupo:
    -- las administra el producto, no un laboratorio.
    IF NEW.tenant_id IS NULL THEN
        RETURN NEW;
    END IF;

    IF NEW.activo AND (SELECT COUNT(*) FROM plantillas_cotizacion
                        WHERE activo
                          AND tenant_id = NEW.tenant_id
                          AND id <> COALESCE(NEW.id, -1)) >= 3 THEN
        RAISE EXCEPTION 'Máximo 3 plantillas activas. Desactive una antes de crear otra.'
            USING ERRCODE = 'restrict_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
COMMENT ON FUNCTION fn_max_plantillas_activas() IS
    'El cupo de 3 es POR TENANT y cuenta solo las propias; las base del producto no consumen cupo.';


-- ----------------------------------------------------------------------------
-- 6c. LAS 8 VISTAS, CONSCIENTES DEL TENANT
-- ----------------------------------------------------------------------------
-- Las ocho leen tablas tenant-scoped y ninguna filtraba por tenant. Se recrean
-- con dos cambios y ninguno más: se expone tenant_id y se declara
-- security_invoker = true.
--
-- POR QUÉ security_invoker (PostgreSQL 15+; aquí corre 16.15):
-- una vista normal se ejecuta con los privilegios de SU DUEÑO, no de quien
-- consulta. Si el dueño de la vista es también dueño de las tablas, las
-- políticas RLS no se le aplican y la vista se convierte en un túnel que
-- atraviesa el aislamiento entero. Con security_invoker las políticas se
-- evalúan como el rol que consulta, que es lo único que tiene sentido.
-- Hoy no cambia nada porque RLS aún no existe; cuando llegue 0004, la
-- diferencia está entre estar aislado y creer que se está.
--
-- POR QUÉ ADEMÁS SE EXPONE tenant_id:
-- para que la API pueda filtrar explícitamente. RLS es la red, no el piso.
--
-- LO QUE NO SE HIZO, Y ES LO IMPORTANTE:
-- agregar tenant_id a un JOIN no es gratis. Tres de estas vistas pierden filas
-- —muchas— si el tenant se amarra en el sitio equivocado. Va comentado en cada
-- una. Los números salen de la base real validada en la fase 2.

DROP VIEW vw_catalogo_disponible;
DROP VIEW vw_paquete_detalle;
DROP VIEW vw_paquetes_resumen;
DROP VIEW vw_acreditacion_vigente;
DROP VIEW vw_resumen_por_categoria;
DROP VIEW vw_ensayos_mas_cotizados;
DROP VIEW vw_auditoria_legible;
DROP VIEW vw_cotizacion_pdf;

-- 1/8 · Tablas base: ensayos_catalogo, subcategorias_ensayo, categorias_ensayo.
-- tenant_id sale de ec (el ensayo). Los JOIN llevan además el tenant: es
-- redundante —la FK compuesta (tenant_id, categoria_id, subcategoria_id) ya lo
-- garantiza— pero deja la intención escrita en la propia vista.
-- Sin riesgo de duplicación (los JOIN son contra la PK) ni de pérdida de filas.
CREATE VIEW vw_catalogo_disponible WITH (security_invoker = true) AS
SELECT ec.tenant_id,
       ce.id   AS categoria_id, ce.slug AS categoria_slug, ce.nombre AS categoria,
       ce.icono, ce.color_hex, ce.orden AS orden_categoria,
       se.id   AS subcategoria_id, se.nombre AS subcategoria, se.orden AS orden_subcategoria,
       ec.id   AS ensayo_id, ec.public_id, ec.codigo, ec.nombre, ec.norma,
       ec.unidad, ec.precio_base, ec.es_paquete, ec.acreditado
  FROM ensayos_catalogo ec
  JOIN subcategorias_ensayo se ON se.id = ec.subcategoria_id AND se.tenant_id = ec.tenant_id
  JOIN categorias_ensayo   ce ON ce.id = ec.categoria_id     AND ce.tenant_id = ec.tenant_id
 WHERE ec.activo AND se.activo AND ce.activo;

-- 2/8 · Tablas base: paquete_componentes, ensayos_catalogo (dos veces).
-- tenant_id sale de pc (el componente).
-- PÉRDIDA DE FILAS: el segundo JOIN es LEFT y su condición de tenant va en el
-- ON, nunca en el WHERE. Movida al WHERE, el LEFT JOIN se degrada a INNER y
-- desaparecen los componentes descriptivos sin ensayo vinculado: 45 de 122 en
-- la base actual, el 37%. Son justamente los que el control G7 de
-- 99_verificacion.sql contabiliza como pendientes de amarrar al catálogo.
CREATE VIEW vw_paquete_detalle WITH (security_invoker = true) AS
SELECT pc.tenant_id,
       p.id     AS paquete_id,
       p.codigo AS paquete_codigo,
       p.nombre AS paquete,
       pc.orden,
       c.codigo                      AS componente_codigo,
       COALESCE(c.nombre, pc.nombre) AS componente,
       COALESCE(c.norma,  pc.norma)  AS norma,
       pc.cantidad,
       c.precio_base                 AS precio_individual,
       c.activo                      AS componente_activo,
       (pc.ensayo_componente_id IS NOT NULL) AS vinculado
  FROM paquete_componentes pc
  JOIN ensayos_catalogo p      ON p.id = pc.ensayo_id
                              AND p.tenant_id = pc.tenant_id
  LEFT JOIN ensayos_catalogo c ON c.id = pc.ensayo_componente_id
                              AND c.tenant_id = pc.tenant_id;

-- 3/8 · Tablas base: ensayos_catalogo (paquete y componente), paquete_componentes.
-- tenant_id sale de p (el paquete) y entra también en el GROUP BY. No altera la
-- agrupación: ya se agrupaba por p.id, que es PK y por tanto determina el
-- tenant. Mismos LEFT JOIN con la condición de tenant en el ON, por la misma
-- razón que la vista anterior: un paquete con componentes descriptivos debe
-- seguir contándolos.
CREATE VIEW vw_paquetes_resumen WITH (security_invoker = true) AS
SELECT p.tenant_id, p.id, p.codigo, p.nombre, p.precio_base AS precio_paquete, p.activo,
       COUNT(pc.id)                    AS componentes,
       COUNT(pc.ensayo_componente_id)  AS vinculados,
       SUM(c.precio_base * pc.cantidad) AS valor_individual,
       CASE WHEN COUNT(pc.id) = COUNT(pc.ensayo_componente_id)
             AND SUM(c.precio_base * pc.cantidad) > 0
            THEN round(100 * (1 - p.precio_base / SUM(c.precio_base * pc.cantidad)), 1)
       END AS ahorro_pct
  FROM ensayos_catalogo p
  LEFT JOIN paquete_componentes pc ON pc.ensayo_id = p.id
                                  AND pc.tenant_id = p.tenant_id
  LEFT JOIN ensayos_catalogo c     ON c.id = pc.ensayo_componente_id
                                  AND c.tenant_id = p.tenant_id
 WHERE p.es_paquete
 GROUP BY p.tenant_id, p.id, p.codigo, p.nombre, p.precio_base, p.activo;

-- 4/8 · Tablas base: ensayos_catalogo, ensayo_acreditacion_historial (LATERAL).
-- tenant_id sale de ec. El LATERAL filtra además por tenant.
-- CAMBIO DE COMPORTAMIENTO: esta vista llama a fn_hoy_lima(), que tras esta
-- migración resuelve la zona horaria del tenant en contexto. Consultarla sin
-- app.tenant_id deja de funcionar y lanza 42501. No es un defecto de la vista:
-- es la consecuencia de que la fecha de negocio dejó de ser la del servidor.
CREATE VIEW vw_acreditacion_vigente WITH (security_invoker = true) AS
SELECT ec.tenant_id,
       ec.id AS ensayo_id, ec.codigo, ec.nombre, ec.acreditado AS estado_actual,
       h.acreditado AS estado_historial, h.vigente_desde, h.motivo,
       (ec.acreditado = h.acreditado) AS coherente
  FROM ensayos_catalogo ec
  LEFT JOIN LATERAL (
        SELECT acreditado, vigente_desde, motivo
          FROM ensayo_acreditacion_historial
         WHERE ensayo_id = ec.id
           AND tenant_id = ec.tenant_id
           AND vigente_desde <= fn_hoy_lima()
         ORDER BY vigente_desde DESC, id DESC LIMIT 1
  ) h ON TRUE;

-- 5/8 · Tablas base: cotizacion_items, cotizaciones.
-- tenant_id sale de ci y entra en el GROUP BY.
-- CAMBIO REAL DE GRANULARIDAD: antes había una fila por categoría; ahora una
-- por (tenant, categoría). Dentro de un tenant el resultado es idéntico, que es
-- como la consulta la aplicación. Se comprobó que ninguna función ni vista
-- depende de ésta, así que el cambio no arrastra a nadie.
CREATE VIEW vw_resumen_por_categoria WITH (security_invoker = true) AS
SELECT ci.tenant_id,
       ci.categoria_snapshot AS categoria,
       COUNT(DISTINCT c.id)  AS cotizaciones,
       SUM(ci.cantidad)      AS items,
       SUM(ci.subtotal)      AS monto_cotizado,
       SUM(ci.subtotal) FILTER (WHERE c.estado = 'aceptada') AS monto_aceptado
  FROM cotizacion_items ci
  JOIN cotizaciones c ON c.id = ci.cotizacion_id
                     AND c.tenant_id = ci.tenant_id
 WHERE c.estado <> 'borrador'
 GROUP BY ci.tenant_id, ci.categoria_snapshot;

-- 6/8 · Tablas base: cotizacion_items, cotizaciones. Mismo caso que la anterior.
-- El GROUP BY pasa de posiciones (1,2,3) a columnas con nombre: al insertar
-- tenant_id como primera columna las posiciones se corrían, y el error habría
-- sido silencioso — agrupando por las columnas equivocadas sin avisar.
CREATE VIEW vw_ensayos_mas_cotizados WITH (security_invoker = true) AS
SELECT ci.tenant_id,
       ci.codigo_snapshot AS codigo, ci.nombre_snapshot AS nombre,
       ci.categoria_snapshot AS categoria,
       COUNT(*)         AS veces_cotizado,
       SUM(ci.cantidad) AS unidades,
       SUM(ci.subtotal) AS monto
  FROM cotizacion_items ci
  JOIN cotizaciones c ON c.id = ci.cotizacion_id
                     AND c.tenant_id = ci.tenant_id
 WHERE c.estado <> 'borrador'
 GROUP BY ci.tenant_id, ci.codigo_snapshot, ci.nombre_snapshot, ci.categoria_snapshot;

-- 7/8 · Tablas base: auditoria, usuarios, roles.
-- tenant_id sale de a, y aquí PUEDE SER NULL: es el cambio global de la
-- decisión A. La vista lo propaga tal cual.
-- PÉRDIDA DE FILAS, la peor de las tres: el JOIN contra usuarios NO lleva
-- condición de tenant, y no es un olvido. El usuario sistema (id 1) es global:
-- esta misma migración le pone tenant_id = NULL. Amarrar
-- u.tenant_id = a.tenant_id borraría de la vista TODO cambio hecho por
-- sistema: 340 de 341 filas en la base actual, el 99.7%. El aislamiento de
-- esta vista lo da a.tenant_id y la política RLS de auditoria, nunca el JOIN
-- con el autor del cambio.
CREATE VIEW vw_auditoria_legible WITH (security_invoker = true) AS
SELECT a.tenant_id,
       a.id, a.registrado_en, a.tabla, a.registro_id, a.accion,
       (u.nombres || ' ' || u.apellidos) AS usuario, r.codigo AS rol,
       a.ip_origen,
       array_to_string(a.campos_cambiados, ', ') AS campos,
       a.datos_anteriores, a.datos_nuevos
  FROM auditoria a
  JOIN usuarios u ON u.id = a.usuario_id
  JOIN roles    r ON r.id = u.rol_id;

-- 8/8 · Tablas base: cotizaciones, empresas, personas, contactos,
--       plantillas_cotizacion, cotizacion_items (subconsulta).
-- tenant_id sale de c (la cotización).
-- PÉRDIDA DE FILAS: el JOIN con plantillas_cotizacion es INNER y la tabla es
-- HÍBRIDA. Escribir pl.tenant_id = c.tenant_id elimina toda cotización que use
-- una plantilla base: 2 de 2 en la base actual, el 100% de la vista, que es
-- justamente la que alimenta el PDF. La condición correcta admite la base:
--     pl.tenant_id IS NULL OR pl.tenant_id = c.tenant_id
-- que es literalmente la misma regla que aplica el trigger a_validar_plantilla.
-- La subconsulta de ítems lleva su propio filtro de tenant.
CREATE VIEW vw_cotizacion_pdf WITH (security_invoker = true) AS
SELECT c.tenant_id,
       c.id, c.public_id, c.numero, c.fecha_emision, c.estado, c.moneda,
       c.proyecto_nombre, c.validez_dias,
       COALESCE(e.razon_social, p.nombres || ' ' || p.apellidos) AS cliente,
       COALESCE(e.ruc, p.dni)            AS documento_cliente,
       ct.nombres || ' ' || ct.apellidos AS contacto,
       ct.cargo AS contacto_cargo, ct.email AS contacto_email,
       pl.nombre AS plantilla, pl.terminos_condiciones,
       c.subtotal, c.igv_tasa, c.igv, c.descuento_tipo, c.descuento_monto,
       c.descuento_razon, c.total, c.notas,
       (SELECT jsonb_agg(jsonb_build_object(
                  'orden', i.orden, 'codigo', i.codigo_snapshot,
                  'nombre', i.nombre_snapshot, 'norma', i.norma_snapshot,
                  'unidad', i.unidad_snapshot, 'acreditado', i.acreditado_snapshot,
                  'cantidad', i.cantidad, 'precio', i.precio_unitario,
                  'subtotal', i.subtotal, 'incluye', i.componentes_snapshot)
              ORDER BY i.orden)
          FROM cotizacion_items i
         WHERE i.cotizacion_id = c.id AND i.tenant_id = c.tenant_id) AS items
  FROM cotizaciones c
  LEFT JOIN empresas  e  ON e.id  = c.empresa_id  AND e.tenant_id  = c.tenant_id
  LEFT JOIN personas  p  ON p.id  = c.persona_id  AND p.tenant_id  = c.tenant_id
  LEFT JOIN contactos ct ON ct.id = c.contacto_id AND ct.tenant_id = c.tenant_id
  JOIN plantillas_cotizacion pl ON pl.id = c.plantilla_id
                               AND (pl.tenant_id IS NULL OR pl.tenant_id = c.tenant_id);

COMMENT ON VIEW vw_auditoria_legible IS
    'ATENCION: la columna `rol` muestra el rol ACTUAL del usuario, no el que tenia cuando ocurrio el hecho. Si sus roles cambian, esta vista reescribe el pasado. Se corrige en 0006 con un snapshot de roles; hasta entonces, no construir encima de esa columna.';
COMMENT ON VIEW vw_resumen_por_categoria IS
    'Se agrupa por (tenant, categoria_snapshot): el dashboard no pierde historia si el catálogo cambia.';
COMMENT ON VIEW vw_cotizacion_pdf IS
    'Fuente única del PDF. Todo sale del snapshot del ítem, nunca del catálogo vivo.';


-- campos_sensibles se audita a si misma. Va aqui, despues de reemplazar
-- fn_auditar(), para que la primera fila que registre ya use la version nueva.
-- Su tenant_id saldra NULL, que es lo correcto: es un cambio del producto.
CREATE TRIGGER trg_auditar AFTER INSERT OR UPDATE OR DELETE ON campos_sensibles
    FOR EACH ROW EXECUTE FUNCTION fn_auditar();

INSERT INTO schema_migrations (version, nombre, nota) VALUES
    ('0003', 'multi-tenant: tenant_id, unicidad por tenant y FK compuestas',
     'Estructura de aislamiento, vistas tenant-aware y cupo de plantillas por tenant. RLS y autorización de aplicación quedan pendientes (ver bloque 7).');

COMMIT;


-- ============================================================================
-- 7. BLOQUE NO EJECUTABLE — ROW LEVEL SECURITY (fase posterior)
-- ============================================================================
-- Queda escrito para que la decisión esté tomada, pero NO se aplica en 0003:
-- RLS sin un backend que fije app.tenant_id en cada transacción deja la
-- aplicación sin ver nada, y activarlo a medias es peor que no activarlo.
--
-- Condiciones para habilitarlo:
--   · el backend conecta con un rol SIN BYPASSRLS y sin ser dueño de las tablas
--     (el dueño de una tabla ignora sus propias políticas salvo FORCE);
--   · toda transacción empieza con SET LOCAL app.tenant_id;
--   · hay pruebas que verifican que, con el tenant A en contexto, un SELECT sin
--     WHERE no devuelve NI UNA fila del tenant B.
--
-- ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE empresas FORCE  ROW LEVEL SECURITY;
-- CREATE POLICY p_tenant ON empresas
--     USING       (tenant_id = fn_app_tenant())
--     WITH CHECK  (tenant_id = fn_app_tenant());
--   -- USING filtra lo que se LEE; WITH CHECK impide ESCRIBIR en otro tenant.
--   -- Faltando WITH CHECK, un INSERT con tenant_id ajeno pasa sin ruido.
--
-- … y lo mismo para: contactos, personas, categorias_ensayo,
--   subcategorias_ensayo, ensayos_catalogo, ensayo_acreditacion_historial,
--   paquete_componentes, correlativos, cotizaciones, cotizacion_items,
--   cotizacion_historial_estados, integraciones, documentos_externos.
--
-- auditoria es HÍBRIDA por la decisión A: tenant_id NULL = cambio global del
-- producto. Su política es la de abajo, no la simple:
-- CREATE POLICY p_tenant ON auditoria
--     USING      (tenant_id IS NULL OR tenant_id = fn_app_tenant())
--     WITH CHECK (tenant_id IS NULL OR tenant_id = fn_app_tenant());
--   -- El WITH CHECK admite NULL porque quien escribe aquí es SIEMPRE el
--   -- trigger fn_auditar(), nunca una sentencia de la aplicación: la tabla es
--   -- append-only y no acepta INSERT directo. Si 0004 prefiriera cerrar el
--   -- WITH CHECK a (tenant_id = fn_app_tenant()), entonces fn_auditar() SÍ
--   -- necesitaría SECURITY DEFINER para poder sellar los cambios globales.
--
-- SOBRE SECURITY DEFINER EN fn_auditar() — analizado y NO implementado aquí:
--   No hace falta en 0003, porque 0003 no activa RLS y sin políticas el
--   trigger escribe sin obstáculo. Declararlo ahora solo añadiría superficie
--   de ataque sin resolver nada. Cuando 0004 lo evalúe, debe decidir a la vez:
--     · propietario — una función SECURITY DEFINER corre con los privilegios
--       de su dueño, así que el dueño no puede ser un superusuario;
--     · search_path — obligatorio fijarlo (SET search_path = public, pg_temp)
--       o un esquema intruso en el search_path del invocador puede secuestrar
--       la resolución de nombres dentro de la función;
--     · permisos — REVOKE EXECUTE FROM PUBLIC y conceder solo a lo necesario;
--     · riesgo — la función deja de estar sujeta a las políticas del invocador,
--       de modo que un fallo en su lógica de tenant ya no lo atrapa RLS.
--   La alternativa (el WITH CHECK permisivo de arriba) evita todo eso y es la
--   recomendada, porque la protección real de auditoria es el append-only.
--
-- plantillas_cotizacion (híbrida) lleva una política distinta:
-- CREATE POLICY p_tenant ON plantillas_cotizacion
--     USING      (tenant_id IS NULL OR tenant_id = fn_app_tenant())
--     WITH CHECK (tenant_id = fn_app_tenant());
--   -- se LEEN las base y las propias; solo se ESCRIBEN las propias.
--
-- usuarios: igual que plantillas (el usuario "sistema" es global).
-- roles, tenants, schema_migrations: sin RLS (globales, solo lectura para la app).
-- ============================================================================
