-- ============================================================================
--  ⚠  MIGRACIÓN 0003 — MULTI-TENANT ·  ESCRITA, **NO APLICADA**  ⚠
-- ============================================================================
-- ESTE ARCHIVO NO SE EJECUTA EN LA FASE ACTUAL.
--
-- Existe por una razón concreta: la decisión de cómo se aísla un tenant NO se
-- puede improvisar el día que llegue el segundo laboratorio. Si se improvisa,
-- se termina "agregando tenant_id" a las tablas y confiando en que cada
-- consulta del backend recuerde filtrarlo — que es exactamente el camino a una
-- fuga de datos entre clientes. Así que la decisión se toma ahora, se escribe
-- ahora, se revisa ahora, y se aplica cuando toque.
--
-- Precondiciones para aplicarla, TODAS:
--   1. La migración 0002 está aplicada y 99_verificacion.sql sale limpio.
--   2. Existe un backend que resuelve el tenant desde la SESIÓN AUTENTICADA
--      (nunca desde un parámetro, un header o el body del request).
--   3. Ese backend abre cada transacción con  SET LOCAL app.tenant_id = '<n>'.
--   4. Hay pruebas de aislamiento automatizadas (ver el skill /multi-tenant).
--   5. Hay respaldo verificado y ventana de mantenimiento.
--
-- Estado de esta migración: verificada sintácticamente y de extremo a extremo
-- sobre una copia desechable de la base (se aplica, los datos existentes
-- quedan en el tenant 1 y 99_verificacion.sql sigue limpio). La base del
-- proyecto NO la tiene aplicada.
--
-- Lo que este archivo NO trae y es responsabilidad del backend:
--   · autenticación, JWT, sesiones, login;
--   · autorización por rol;
--   · resolución del tenant a partir del usuario;
--   · aislamiento en caché, colas, logs y almacenamiento de archivos.
--   La BD es la última línea de defensa, no la única.
-- ============================================================================

\echo '*** 0003 es una migración PREPARADA, no aplicada. Lea la cabecera. ***'
\set ON_ERROR_STOP on
BEGIN;

-- ----------------------------------------------------------------------------
-- 1. LA TABLA DE TENANTS
-- ----------------------------------------------------------------------------
-- [GLOBAL] Un tenant = un laboratorio cliente del SaaS. GTQC es el tenant 1.
CREATE TABLE tenants (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id       UUID         NOT NULL DEFAULT gen_random_uuid(),
    slug            VARCHAR(40)  NOT NULL CHECK (slug ~ '^[a-z0-9-]{2,40}$'),
    razon_social    VARCHAR(200) NOT NULL,
    ruc             dom_ruc      NOT NULL,
    zona_horaria    VARCHAR(40)  NOT NULL DEFAULT 'America/Lima',
    plan            VARCHAR(20)  NOT NULL DEFAULT 'estandar',
    activo          BOOLEAN      NOT NULL DEFAULT TRUE,
    suspendido_en   TIMESTAMPTZ,
    creado_en       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT uq_tenants_public_id UNIQUE (public_id),
    CONSTRAINT uq_tenants_slug      UNIQUE (slug),
    CONSTRAINT uq_tenants_ruc       UNIQUE (ruc)
);
COMMENT ON TABLE tenants IS 'GLOBAL. Un laboratorio cliente del SaaS.';
-- zona_horaria por tenant: hoy fn_hoy_lima() fija America/Lima porque hay un
-- solo laboratorio. Con varios, la fecha de emisión debe salir de la zona del
-- tenant, no del servidor.

INSERT INTO tenants (id, slug, razon_social, ruc)
VALUES (1, 'gtqc', 'Group Total Quality Control S.A.C.', '20601234567');
SELECT setval(pg_get_serial_sequence('tenants','id'), 1);

-- Resolución del tenant activo. Sin contexto NO adivina: lanza error.
-- Es lo contrario de fn_app_usuario(), que sí tiene fallback: un cambio sin
-- autor identificado es un bug molesto; una consulta sin tenant identificado
-- es una fuga de datos entre clientes.
CREATE OR REPLACE FUNCTION fn_app_tenant() RETURNS INTEGER AS $$
DECLARE v INTEGER := NULLIF(current_setting('app.tenant_id', TRUE), '')::INTEGER;
BEGIN
    IF v IS NULL THEN
        RAISE EXCEPTION 'No hay tenant en el contexto de la sesión'
            USING ERRCODE = 'insufficient_privilege',
                  HINT = 'El backend debe ejecutar SET LOCAL app.tenant_id antes de cualquier consulta.';
    END IF;
    RETURN v;
END;
$$ LANGUAGE plpgsql STABLE;


-- ----------------------------------------------------------------------------
-- 2. tenant_id EN LAS TABLAS TENANT-SCOPED
-- ----------------------------------------------------------------------------
-- NO se agrega a ciegas. La clasificación razonada, tabla por tabla, está en
-- docs/AUDITORIA_BD_v3.md (sección "GLOBAL vs TENANT-SCOPED").
--
-- QUEDAN GLOBALES (sin tenant_id):
--   schema_migrations · tenants · roles
--   Motivo: son del producto. Los 4 roles son los mismos para todos; si un
--   laboratorio necesitara roles propios, se agregaría una tabla
--   roles_tenant aparte en vez de duplicar los básicos 1000 veces.
--
-- SON TENANT-SCOPED (llevan tenant_id):
--   usuarios, empresas, contactos, personas, categorias_ensayo,
--   subcategorias_ensayo, ensayos_catalogo, ensayo_acreditacion_historial,
--   paquete_componentes, correlativos, cotizaciones, cotizacion_items,
--   cotizacion_historial_estados, integraciones, documentos_externos, auditoria
--
-- ES HÍBRIDA:
--   plantillas_cotizacion — tenant_id NULL = plantilla base del producto,
--   visible para todos; tenant_id = N = plantilla propia de ese laboratorio.
--
-- Nota sobre las tablas HIJAS (cotizacion_items, paquete_componentes,
-- historiales): se les agrega tenant_id aunque sean alcanzables solo por su
-- padre. Razón: sin la columna, la política RLS de la hija tendría que hacer
-- un subquery al padre en cada fila leída, y un JOIN mal escrito en un reporte
-- se salta el aislamiento. Con la columna, la FK compuesta hace que sea
-- imposible que una hija pertenezca a otro tenant que su padre.

ALTER TABLE usuarios                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE empresas                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE contactos                     ADD COLUMN tenant_id INTEGER;
ALTER TABLE personas                      ADD COLUMN tenant_id INTEGER;
ALTER TABLE categorias_ensayo             ADD COLUMN tenant_id INTEGER;
ALTER TABLE subcategorias_ensayo          ADD COLUMN tenant_id INTEGER;
ALTER TABLE ensayos_catalogo              ADD COLUMN tenant_id INTEGER;
ALTER TABLE ensayo_acreditacion_historial ADD COLUMN tenant_id INTEGER;
ALTER TABLE paquete_componentes           ADD COLUMN tenant_id INTEGER;
ALTER TABLE correlativos                  ADD COLUMN tenant_id INTEGER;
ALTER TABLE plantillas_cotizacion         ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizaciones                  ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizacion_items              ADD COLUMN tenant_id INTEGER;
ALTER TABLE cotizacion_historial_estados  ADD COLUMN tenant_id INTEGER;
ALTER TABLE integraciones                 ADD COLUMN tenant_id INTEGER;
ALTER TABLE documentos_externos           ADD COLUMN tenant_id INTEGER;
ALTER TABLE auditoria                     ADD COLUMN tenant_id INTEGER;

-- Todo lo existente es del tenant 1 (GTQC).
--
-- El relleno necesita desactivar los triggers de usuario mientras dura: las
-- tablas append-only (auditoria, los dos historiales) rechazan cualquier
-- UPDATE, y a_congelar rechaza tocar una cotización ya emitida. Eso es
-- justamente lo que deben hacer en operación normal; aquí se apagan de forma
-- explícita y acotada, y se vuelven a encender antes de terminar. Las FK
-- siguen activas: DISABLE TRIGGER USER no toca los triggers del sistema.
DO $apagar$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'usuarios','empresas','contactos','personas','categorias_ensayo',
        'subcategorias_ensayo','ensayos_catalogo','ensayo_acreditacion_historial',
        'paquete_componentes','plantillas_cotizacion','cotizaciones','cotizacion_items',
        'cotizacion_historial_estados','integraciones','documentos_externos','auditoria']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I DISABLE TRIGGER USER', r.t);
    END LOOP;
END
$apagar$;

UPDATE usuarios                      SET tenant_id = 1;
UPDATE empresas                      SET tenant_id = 1;
UPDATE contactos                     SET tenant_id = 1;
UPDATE personas                      SET tenant_id = 1;
UPDATE categorias_ensayo             SET tenant_id = 1;
UPDATE subcategorias_ensayo          SET tenant_id = 1;
UPDATE ensayos_catalogo              SET tenant_id = 1;
UPDATE ensayo_acreditacion_historial SET tenant_id = 1;
UPDATE paquete_componentes           SET tenant_id = 1;
UPDATE correlativos                  SET tenant_id = 1;
UPDATE cotizaciones                  SET tenant_id = 1;
UPDATE cotizacion_items              SET tenant_id = 1;
UPDATE cotizacion_historial_estados  SET tenant_id = 1;
UPDATE integraciones                 SET tenant_id = 1;
UPDATE documentos_externos           SET tenant_id = 1;
UPDATE auditoria                     SET tenant_id = 1;
-- Las 3 plantillas base pasan a ser del producto (tenant_id NULL), visibles
-- para todos los laboratorios; las que cree cada uno llevarán su tenant_id.
UPDATE plantillas_cotizacion SET tenant_id = NULL WHERE slug IN ('estandar','premium','express');

-- El usuario "sistema" (id = 1) es el único usuario global: es el autor de los
-- seeds y el fallback de auditoría de TODOS los tenants.
UPDATE usuarios SET tenant_id = NULL WHERE id = 1;

-- Triggers de vuelta. A partir de aquí la base protege igual que antes.
DO $encender$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'usuarios','empresas','contactos','personas','categorias_ensayo',
        'subcategorias_ensayo','ensayos_catalogo','ensayo_acreditacion_historial',
        'paquete_componentes','plantillas_cotizacion','cotizaciones','cotizacion_items',
        'cotizacion_historial_estados','integraciones','documentos_externos','auditoria']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I ENABLE TRIGGER USER', r.t);
    END LOOP;
END
$encender$;

DO $obligatorio$
DECLARE r RECORD;
BEGIN
    FOR r IN SELECT unnest(ARRAY[
        'empresas','contactos','personas','categorias_ensayo','subcategorias_ensayo',
        'ensayos_catalogo','ensayo_acreditacion_historial','paquete_componentes',
        'correlativos','cotizaciones','cotizacion_items','cotizacion_historial_estados',
        'integraciones','documentos_externos','auditoria']) AS t
    LOOP
        EXECUTE format('ALTER TABLE %I ALTER COLUMN tenant_id SET NOT NULL', r.t);
        EXECUTE format('ALTER TABLE %I ADD CONSTRAINT %I FOREIGN KEY (tenant_id)
                        REFERENCES tenants(id) ON DELETE RESTRICT',
                       r.t, 'fk_' || r.t || '_tenant');
        EXECUTE format('ALTER TABLE %I ALTER COLUMN tenant_id SET DEFAULT fn_app_tenant()', r.t);
    END LOOP;
END
$obligatorio$;

-- usuarios y plantillas_cotizacion admiten NULL (fila global del producto).
ALTER TABLE usuarios ADD CONSTRAINT fk_usuarios_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;
ALTER TABLE plantillas_cotizacion ADD CONSTRAINT fk_plantillas_tenant
    FOREIGN KEY (tenant_id) REFERENCES tenants(id) ON DELETE RESTRICT;


-- ----------------------------------------------------------------------------
-- 3. UNICIDAD: DE GLOBAL A "POR TENANT"
-- ----------------------------------------------------------------------------
-- Esto es lo que más se olvida y lo que más duele. Si `ruc` sigue siendo único
-- global, el segundo laboratorio no puede registrar a un cliente que el primero
-- ya tenía. Si `codigo` sigue siendo único global, dos laboratorios no pueden
-- tener ambos su SU-01. Y si `numero` sigue siendo único global, el segundo
-- laboratorio empieza a numerar en COT-2026-203.
ALTER TABLE empresas DROP CONSTRAINT uq_empresas_ruc;
ALTER TABLE empresas ADD  CONSTRAINT uq_empresas_ruc UNIQUE (tenant_id, ruc);

ALTER TABLE personas DROP CONSTRAINT uq_personas_dni;
ALTER TABLE personas ADD  CONSTRAINT uq_personas_dni UNIQUE (tenant_id, dni);

ALTER TABLE contactos DROP CONSTRAINT uq_contactos_empresa_dni;
ALTER TABLE contactos ADD  CONSTRAINT uq_contactos_empresa_dni UNIQUE (tenant_id, empresa_id, dni);

ALTER TABLE categorias_ensayo DROP CONSTRAINT uq_categorias_slug;
ALTER TABLE categorias_ensayo ADD  CONSTRAINT uq_categorias_slug UNIQUE (tenant_id, slug);
ALTER TABLE categorias_ensayo DROP CONSTRAINT uq_categorias_prefijo;
ALTER TABLE categorias_ensayo ADD  CONSTRAINT uq_categorias_prefijo UNIQUE (tenant_id, prefijo_codigo);
DROP INDEX uq_categorias_nombre;
CREATE UNIQUE INDEX uq_categorias_nombre ON categorias_ensayo (tenant_id, lower(nombre));

DROP INDEX uq_subcategorias_nombre;
CREATE UNIQUE INDEX uq_subcategorias_nombre
    ON subcategorias_ensayo (tenant_id, categoria_id, lower(nombre));

ALTER TABLE ensayos_catalogo DROP CONSTRAINT uq_ensayos_codigo;
ALTER TABLE ensayos_catalogo ADD  CONSTRAINT uq_ensayos_codigo UNIQUE (tenant_id, codigo);

ALTER TABLE cotizaciones DROP CONSTRAINT uq_cotizaciones_numero;
ALTER TABLE cotizaciones ADD  CONSTRAINT uq_cotizaciones_numero UNIQUE (tenant_id, numero);

ALTER TABLE plantillas_cotizacion DROP CONSTRAINT uq_plantillas_slug;
CREATE UNIQUE INDEX uq_plantillas_slug_tenant ON plantillas_cotizacion (tenant_id, slug)
    WHERE tenant_id IS NOT NULL;
CREATE UNIQUE INDEX uq_plantillas_slug_base   ON plantillas_cotizacion (slug)
    WHERE tenant_id IS NULL;

DROP INDEX uq_usuarios_email;
-- El email sí sigue siendo único en TODO el sistema: una persona = una cuenta.
-- Si mañana la misma persona trabaja para dos laboratorios, se resuelve con
-- una tabla usuario_tenant (pertenencia N:N), no duplicando la identidad.
CREATE UNIQUE INDEX uq_usuarios_email ON usuarios (lower(email));

DROP INDEX uq_integraciones_laboratorio;
CREATE UNIQUE INDEX uq_integraciones_laboratorio
    ON integraciones (tenant_id, proveedor) WHERE empresa_id IS NULL;
ALTER TABLE integraciones DROP CONSTRAINT uq_integraciones_empresa_proveedor;
ALTER TABLE integraciones ADD  CONSTRAINT uq_integraciones_empresa_proveedor
    UNIQUE (tenant_id, empresa_id, proveedor);

-- Correlativos: la PK incluye el tenant, y con eso Tenant A y Tenant B pueden
-- tener ambos su COT-2026-001 y su propio SU-29 sin saber el uno del otro.
ALTER TABLE correlativos DROP CONSTRAINT correlativos_pkey;
ALTER TABLE correlativos ADD  CONSTRAINT correlativos_pkey
    PRIMARY KEY (tenant_id, ambito, clave, periodo);


-- ----------------------------------------------------------------------------
-- 4. FK COMPUESTAS: QUE LA BASE HAGA IMPOSIBLE EL CRUCE DE TENANTS
-- ----------------------------------------------------------------------------
-- Agregar tenant_id NO aísla nada por sí solo. Sin esto, una cotización del
-- Tenant A puede apuntar tranquilamente a una empresa del Tenant B: cada fila
-- cumple su propia FK y su propio tenant_id, y el resultado es una fuga.
--
-- El patrón: la tabla padre declara UNIQUE (tenant_id, id) y la hija referencia
-- ese par. Entonces la pertenencia al mismo tenant no es una regla que el
-- backend deba recordar: es una imposibilidad física en el motor.
-- Es exactamente el mismo mecanismo que v3 ya usa hoy para
-- (empresa_id, contacto_id) y para (categoria_id, subcategoria_id) — por eso
-- esta migración es mecánica y no un rediseño.

ALTER TABLE tenants                  ADD CONSTRAINT uq_tenants_tid           UNIQUE (id);
ALTER TABLE empresas                 ADD CONSTRAINT uq_empresas_tenant_id    UNIQUE (tenant_id, id);
ALTER TABLE contactos                ADD CONSTRAINT uq_contactos_tenant_id   UNIQUE (tenant_id, id);
ALTER TABLE personas                 ADD CONSTRAINT uq_personas_tenant_id    UNIQUE (tenant_id, id);
ALTER TABLE categorias_ensayo        ADD CONSTRAINT uq_categorias_tenant_id  UNIQUE (tenant_id, id);
ALTER TABLE subcategorias_ensayo     ADD CONSTRAINT uq_subcat_tenant_id      UNIQUE (tenant_id, id);
ALTER TABLE ensayos_catalogo         ADD CONSTRAINT uq_ensayos_tenant_id     UNIQUE (tenant_id, id);
ALTER TABLE cotizaciones             ADD CONSTRAINT uq_cotizaciones_tenant_id UNIQUE (tenant_id, id);
ALTER TABLE integraciones            ADD CONSTRAINT uq_integraciones_tenant_id UNIQUE (tenant_id, id);

-- contactos → empresas (mismo tenant)
ALTER TABLE contactos DROP CONSTRAINT contactos_empresa_id_fkey;
ALTER TABLE contactos ADD  CONSTRAINT contactos_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;

-- subcategorias → categorias (mismo tenant)
ALTER TABLE subcategorias_ensayo DROP CONSTRAINT subcategorias_ensayo_categoria_id_fkey;
ALTER TABLE subcategorias_ensayo ADD  CONSTRAINT subcategorias_ensayo_categoria_id_fkey
    FOREIGN KEY (tenant_id, categoria_id) REFERENCES categorias_ensayo (tenant_id, id) ON DELETE RESTRICT;

-- ensayos → subcategorias (mismo tenant Y misma categoría: FK de 3 columnas).
-- Primero cae la FK que cuelga del UNIQUE, después el UNIQUE: al revés,
-- PostgreSQL rechaza el DROP por dependencia.
ALTER TABLE ensayos_catalogo     DROP CONSTRAINT fk_ensayos_subcategoria;
ALTER TABLE subcategorias_ensayo DROP CONSTRAINT uq_subcategorias_categoria_id;
ALTER TABLE subcategorias_ensayo ADD  CONSTRAINT uq_subcategorias_categoria_id
    UNIQUE (tenant_id, categoria_id, id);
ALTER TABLE ensayos_catalogo ADD  CONSTRAINT fk_ensayos_subcategoria
    FOREIGN KEY (tenant_id, categoria_id, subcategoria_id)
    REFERENCES subcategorias_ensayo (tenant_id, categoria_id, id) ON DELETE RESTRICT;

-- acreditación e componentes → ensayos (mismo tenant)
ALTER TABLE ensayo_acreditacion_historial DROP CONSTRAINT ensayo_acreditacion_historial_ensayo_id_fkey;
ALTER TABLE ensayo_acreditacion_historial ADD  CONSTRAINT ensayo_acreditacion_historial_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE paquete_componentes DROP CONSTRAINT paquete_componentes_ensayo_id_fkey;
ALTER TABLE paquete_componentes ADD  CONSTRAINT paquete_componentes_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE paquete_componentes DROP CONSTRAINT paquete_componentes_ensayo_componente_id_fkey;
ALTER TABLE paquete_componentes ADD  CONSTRAINT paquete_componentes_ensayo_componente_id_fkey
    FOREIGN KEY (tenant_id, ensayo_componente_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE RESTRICT;

-- cotizaciones → cliente (mismo tenant). El contacto sigue amarrado además a
-- su empresa: la FK pasa a ser (tenant_id, empresa_id, contacto_id).
ALTER TABLE cotizaciones DROP CONSTRAINT cotizaciones_empresa_id_fkey;
ALTER TABLE cotizaciones ADD  CONSTRAINT cotizaciones_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizaciones DROP CONSTRAINT cotizaciones_persona_id_fkey;
ALTER TABLE cotizaciones ADD  CONSTRAINT cotizaciones_persona_id_fkey
    FOREIGN KEY (tenant_id, persona_id) REFERENCES personas (tenant_id, id) ON DELETE RESTRICT;
-- Igual que arriba: la FK primero, el UNIQUE del que depende después.
ALTER TABLE cotizaciones DROP CONSTRAINT fk_cotizacion_contacto_de_su_empresa;
ALTER TABLE contactos    DROP CONSTRAINT uq_contactos_empresa_id;
ALTER TABLE contactos    ADD  CONSTRAINT uq_contactos_empresa_id UNIQUE (tenant_id, empresa_id, id);
ALTER TABLE cotizaciones ADD  CONSTRAINT fk_cotizacion_contacto_de_su_empresa
    FOREIGN KEY (tenant_id, empresa_id, contacto_id)
    REFERENCES contactos (tenant_id, empresa_id, id) ON DELETE RESTRICT;

-- ítems, historial y documentos → cotización (mismo tenant)
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_cotizacion_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_ensayo_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_ensayo_id_fkey
    FOREIGN KEY (tenant_id, ensayo_id) REFERENCES ensayos_catalogo (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizacion_items DROP CONSTRAINT cotizacion_items_categoria_id_fkey;
ALTER TABLE cotizacion_items ADD  CONSTRAINT cotizacion_items_categoria_id_fkey
    FOREIGN KEY (tenant_id, categoria_id) REFERENCES categorias_ensayo (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE cotizacion_historial_estados DROP CONSTRAINT cotizacion_historial_estados_cotizacion_id_fkey;
ALTER TABLE cotizacion_historial_estados ADD  CONSTRAINT cotizacion_historial_estados_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE CASCADE;
ALTER TABLE documentos_externos DROP CONSTRAINT documentos_externos_cotizacion_id_fkey;
ALTER TABLE documentos_externos ADD  CONSTRAINT documentos_externos_cotizacion_id_fkey
    FOREIGN KEY (tenant_id, cotizacion_id) REFERENCES cotizaciones (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE documentos_externos DROP CONSTRAINT documentos_externos_integracion_id_fkey;
ALTER TABLE documentos_externos ADD  CONSTRAINT documentos_externos_integracion_id_fkey
    FOREIGN KEY (tenant_id, integracion_id) REFERENCES integraciones (tenant_id, id) ON DELETE RESTRICT;
ALTER TABLE integraciones DROP CONSTRAINT integraciones_empresa_id_fkey;
ALTER TABLE integraciones ADD  CONSTRAINT integraciones_empresa_id_fkey
    FOREIGN KEY (tenant_id, empresa_id) REFERENCES empresas (tenant_id, id) ON DELETE RESTRICT;

-- La plantilla de una cotización: o es base del producto, o es del mismo
-- tenant. Un CHECK de fila no puede mirar otra tabla, así que va por trigger.
CREATE OR REPLACE FUNCTION fn_validar_plantilla_tenant() RETURNS TRIGGER AS $$
DECLARE v_tp INTEGER;
BEGIN
    SELECT tenant_id INTO v_tp FROM plantillas_cotizacion WHERE id = NEW.plantilla_id;
    IF v_tp IS NOT NULL AND v_tp <> NEW.tenant_id THEN
        RAISE EXCEPTION 'La plantilla % pertenece a otro tenant', NEW.plantilla_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;
CREATE TRIGGER a_validar_plantilla BEFORE INSERT OR UPDATE OF plantilla_id, tenant_id ON cotizaciones
    FOR EACH ROW EXECUTE FUNCTION fn_validar_plantilla_tenant();


-- ----------------------------------------------------------------------------
-- 5. ÍNDICES CON EL TENANT AL FRENTE
-- ----------------------------------------------------------------------------
-- Toda consulta del sistema llevará WHERE tenant_id = N. Un índice que no
-- empiece por tenant_id obliga a filtrar después de leer, y el rendimiento se
-- degrada con cada laboratorio nuevo.
DROP INDEX idx_cotizaciones_fecha;
CREATE INDEX idx_cotizaciones_fecha ON cotizaciones (tenant_id, fecha_emision)
    WHERE estado <> 'borrador';
DROP INDEX idx_cotizaciones_estado_fecha;
CREATE INDEX idx_cotizaciones_estado_fecha ON cotizaciones (tenant_id, estado, fecha_emision DESC);
DROP INDEX idx_catalogo_navegacion;
CREATE INDEX idx_catalogo_navegacion
    ON ensayos_catalogo (tenant_id, categoria_id, subcategoria_id, codigo) WHERE activo;
DROP INDEX idx_auditoria_registro;
CREATE INDEX idx_auditoria_registro ON auditoria (tenant_id, tabla, registro_id);
DROP INDEX idx_auditoria_fecha;
CREATE INDEX idx_auditoria_fecha ON auditoria (tenant_id, registrado_en DESC);
CREATE INDEX idx_items_tenant_categoria ON cotizacion_items (tenant_id, categoria_id);

-- Las tablas hijas cuyo tenant_id quedó sin índice líder: lo necesitan tanto
-- para la FK a tenants como para que la futura política RLS filtre por índice
-- en lugar de leer la tabla completa. Las demás ya están cubiertas por su
-- UNIQUE (tenant_id, …) o por los índices compuestos de arriba.
CREATE INDEX idx_usuarios_tenant       ON usuarios (tenant_id);
CREATE INDEX idx_acreditacion_tenant   ON ensayo_acreditacion_historial (tenant_id, ensayo_id);
CREATE INDEX idx_componentes_tenant    ON paquete_componentes (tenant_id, ensayo_id);
CREATE INDEX idx_hist_estados_tenant   ON cotizacion_historial_estados (tenant_id, cotizacion_id);
CREATE INDEX idx_documentos_tenant     ON documentos_externos (tenant_id, cotizacion_id);


-- ----------------------------------------------------------------------------
-- 6. FUNCIONES CONSCIENTES DEL TENANT
-- ----------------------------------------------------------------------------
-- El correlativo se vuelve por tenant. Nada más cambia en su lógica: sigue
-- siendo un INSERT ... ON CONFLICT DO UPDATE atómico.
CREATE OR REPLACE FUNCTION fn_siguiente_correlativo(
    p_ambito VARCHAR, p_clave VARCHAR, p_periodo VARCHAR
) RETURNS INTEGER AS $$
DECLARE v_valor INTEGER;
BEGIN
    INSERT INTO correlativos (tenant_id, ambito, clave, periodo, ultimo)
    VALUES (fn_app_tenant(), p_ambito, p_clave, p_periodo, 1)
    ON CONFLICT (tenant_id, ambito, clave, periodo)
    DO UPDATE SET ultimo = correlativos.ultimo + 1, actualizado_en = now()
    RETURNING ultimo INTO v_valor;
    RETURN v_valor;
END;
$$ LANGUAGE plpgsql;

-- La fecha de negocio sale de la zona horaria DEL TENANT, no del servidor.
CREATE OR REPLACE FUNCTION fn_hoy_lima() RETURNS DATE AS $$
    SELECT (now() AT TIME ZONE COALESCE(
        (SELECT zona_horaria FROM tenants WHERE id = fn_app_tenant()), 'America/Lima'))::date;
$$ LANGUAGE sql STABLE;
COMMENT ON FUNCTION fn_hoy_lima() IS
    'Conserva el nombre por compatibilidad; ahora resuelve la zona del tenant.';

-- El validador del prefijo del código debe mirar la categoría DEL MISMO tenant.
CREATE OR REPLACE FUNCTION fn_validar_codigo_ensayo() RETURNS TRIGGER AS $$
DECLARE v_prefijo VARCHAR(3);
BEGIN
    SELECT prefijo_codigo INTO v_prefijo FROM categorias_ensayo
     WHERE id = NEW.categoria_id AND tenant_id = NEW.tenant_id;
    IF v_prefijo IS NULL THEN
        RAISE EXCEPTION 'La categoría % no existe en este tenant', NEW.categoria_id
            USING ERRCODE = 'insufficient_privilege';
    END IF;
    IF NEW.codigo !~ ('^' || v_prefijo || '-[0-9]{2,4}$') THEN
        RAISE EXCEPTION 'El código "%" no corresponde a la categoría (debe ser %-NN)', NEW.codigo, v_prefijo
            USING ERRCODE = 'check_violation';
    END IF;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- La auditoría también se sella con el tenant.
CREATE OR REPLACE FUNCTION fn_auditar() RETURNS TRIGGER AS $$
DECLARE
    v_new JSONB := CASE WHEN TG_OP <> 'DELETE' THEN to_jsonb(NEW) END;
    v_old JSONB := CASE WHEN TG_OP <> 'INSERT' THEN to_jsonb(OLD) END;
    v_ref JSONB := COALESCE(v_new, v_old);
    v_campos TEXT[];
BEGIN
    IF TG_OP = 'UPDATE' THEN
        SELECT array_agg(k ORDER BY k) INTO v_campos
        FROM jsonb_object_keys(v_new) AS k
        WHERE v_old -> k IS DISTINCT FROM v_new -> k;
        IF v_campos IS NULL OR v_campos <@ ARRAY['actualizado_en','actualizado_por'] THEN
            RETURN NULL;
        END IF;
    END IF;
    INSERT INTO auditoria (tenant_id, tabla, registro_id, registro_public_id, accion,
                           campos_cambiados, datos_anteriores, datos_nuevos, usuario_id, ip_origen)
    VALUES (COALESCE((v_ref->>'tenant_id')::INTEGER, fn_app_tenant()),
            TG_TABLE_NAME, (v_ref->>'id')::BIGINT,
            NULLIF(v_ref->>'public_id','')::UUID, TG_OP, v_campos, v_old, v_new,
            fn_app_usuario(), fn_app_ip());
    RETURN NULL;
END;
$$ LANGUAGE plpgsql;

INSERT INTO schema_migrations (version, nombre, nota) VALUES
    ('0003', 'multi-tenant: tenant_id, unicidad por tenant y FK compuestas',
     'Estructura de aislamiento. RLS y autorización de aplicación quedan pendientes (ver bloque 7).');

COMMIT;


-- ============================================================================
-- 7. BLOQUE NO EJECUTABLE — ROW LEVEL SECURITY (fase posterior)
-- ============================================================================
-- Queda escrito para que la decisión esté tomada, pero NO se aplica en 0003:
-- RLS sin un backend que fije app.tenant_id en cada transacción deja la
-- aplicación sin ver nada, y activarlo a medias es peor que no activarlo.
--
-- Condiciones para habilitarlo:
--   · el backend conecta con un rol SIN BYPASSRLS y sin ser dueño de las tablas
--     (el dueño de una tabla ignora sus propias políticas salvo FORCE);
--   · toda transacción empieza con SET LOCAL app.tenant_id;
--   · hay pruebas que verifican que, con el tenant A en contexto, un SELECT sin
--     WHERE no devuelve NI UNA fila del tenant B.
--
-- ALTER TABLE empresas ENABLE ROW LEVEL SECURITY;
-- ALTER TABLE empresas FORCE  ROW LEVEL SECURITY;
-- CREATE POLICY p_tenant ON empresas
--     USING       (tenant_id = fn_app_tenant())
--     WITH CHECK  (tenant_id = fn_app_tenant());
--   -- USING filtra lo que se LEE; WITH CHECK impide ESCRIBIR en otro tenant.
--   -- Faltando WITH CHECK, un INSERT con tenant_id ajeno pasa sin ruido.
--
-- … y lo mismo para: contactos, personas, categorias_ensayo,
--   subcategorias_ensayo, ensayos_catalogo, ensayo_acreditacion_historial,
--   paquete_componentes, correlativos, cotizaciones, cotizacion_items,
--   cotizacion_historial_estados, integraciones, documentos_externos, auditoria.
--
-- plantillas_cotizacion (híbrida) lleva una política distinta:
-- CREATE POLICY p_tenant ON plantillas_cotizacion
--     USING      (tenant_id IS NULL OR tenant_id = fn_app_tenant())
--     WITH CHECK (tenant_id = fn_app_tenant());
--   -- se LEEN las base y las propias; solo se ESCRIBEN las propias.
--
-- usuarios: igual que plantillas (el usuario "sistema" es global).
-- roles, tenants, schema_migrations: sin RLS (globales, solo lectura para la app).
-- ============================================================================
